// <auto-generated />
using System;
using MatrixNext.Web.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatrixNext.Web.Migrations
{
    [DbContext(typeof(MatrixDbContext))]
    [Migration("20260113001425_Add_EQ_Entities")]
    partial class Add_EQ_Entities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatrixNext.Web.Models.CORE.ObservacionTarea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<long>("IdWorkFlow")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TipoOperacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdWorkFlow", "FechaCreacion")
                        .HasDatabaseName("IX_ObservacionTarea_WorkFlowFecha");

                    b.ToTable("ObservacionesTareas");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.CORE.Tarea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("NoEmpiezaAntesDe")
                        .HasColumnType("bigint");

                    b.Property<long?>("NoTerminaAntesDe")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("Orden")
                        .HasColumnType("bigint");

                    b.Property<bool?>("RequiereEstimacion")
                        .HasColumnType("bit");

                    b.Property<long?>("RolEjecuta")
                        .HasColumnType("bigint");

                    b.Property<long?>("RolEstima")
                        .HasColumnType("bigint");

                    b.Property<short?>("TiempoPromedioDias")
                        .HasColumnType("smallint");

                    b.Property<long?>("UnidadEjecuta")
                        .HasColumnType("bigint");

                    b.Property<long?>("UnidadRecibe")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("Visible");

                    b.ToTable("CORE_Tareas", (string)null);
                });

            modelBuilder.Entity("MatrixNext.Web.Models.CORE.TareaPrevia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdTarea")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdTareaPreviaRequerida")
                        .HasColumnType("bigint");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdTarea");

                    b.HasIndex("IdTareaPreviaRequerida")
                        .HasDatabaseName("IX_TareaPrevia_IdTareaPreviaRequerida");

                    b.ToTable("TareasPrevias");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.CORE.WorkFlow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Creada");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdTarea")
                        .HasColumnType("bigint");

                    b.Property<int>("IdTipoHilo")
                        .HasColumnType("int");

                    b.Property<long>("IdTrabajo")
                        .HasColumnType("bigint");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_WorkFlow_Estado");

                    b.HasIndex("IdTrabajo")
                        .HasDatabaseName("IX_WorkFlow_IdTrabajo");

                    b.ToTable("WorkFlows");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.CORE.WorkFlowUsuarioAsignado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<long>("IdWorkFlow")
                        .HasColumnType("bigint");

                    b.Property<string>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Responsable");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_WorkFlowUsuarioAsignado_IdUsuario");

                    b.HasIndex("IdWorkFlow");

                    b.ToTable("WorkFlowUsuariosAsignados");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqCostInsumos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Dias")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Logistica")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NSE")
                        .HasColumnType("int");

                    b.Property<decimal>("Obsequio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Productividad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Reclutamiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SeguroPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Supervisores")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransporteEncuestador")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransporteSupervisor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorEnvio1erKilo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorKiloAdicional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorMinDeclarar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NSE")
                        .HasDatabaseName("IX_EqCostInsumos_NSE");

                    b.ToTable("eq_cost_insumos");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqCostResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AOTTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AOTUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CompraProducto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoCalidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoCampo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoConIncentivos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoDirectoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DataCleaning")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DirectCostOps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Estadistica")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCalculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("GM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Graficacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Harmoni")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Incentivos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Insumos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Logistica")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("OP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PB_RMF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PctOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Procesamiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuoteHeaderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Scripting")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StaffOps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tablets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TopLines")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Viaticos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteHeaderId")
                        .IsUnique()
                        .HasDatabaseName("IX_EqCostResult_QuoteHeaderId");

                    b.ToTable("eq_cost_result");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqLocaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DiasBase")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TarifaBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TarifaConGross")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ciudad")
                        .HasDatabaseName("IX_EqLocaciones_Ciudad");

                    b.ToTable("eq_locaciones");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqMethodology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseDatos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IncidenciaLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("IncidenciaValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MetodologiaRecoleccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("MetodologiasMix")
                        .HasColumnType("bit");

                    b.Property<int>("QuoteHeaderId")
                        .HasColumnType("int");

                    b.Property<bool>("Tecnica1Flag")
                        .HasColumnType("bit");

                    b.Property<string>("Tecnica1Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Tecnica2Flag")
                        .HasColumnType("bit");

                    b.Property<string>("Tecnica2Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Tecnica3Flag")
                        .HasColumnType("bit");

                    b.Property<string>("Tecnica3Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteHeaderId")
                        .HasDatabaseName("IX_EqMethodology_QuoteHeaderId");

                    b.ToTable("eq_methodology");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqMystery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Alertas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AlquilerEquipos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Complejidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CompraDispositivos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Desplazamientos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EdicionVideo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("NumOlas")
                        .HasColumnType("int");

                    b.Property<int>("QuoteHeaderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Seguimiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tanques")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoVisita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuoteHeaderId")
                        .HasDatabaseName("IX_EqMystery_QuoteHeaderId");

                    b.ToTable("eq_mystery");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqParamPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionMin")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PenetracionRango")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoMetodologia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorCoord")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPerfil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("VigentDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VigentHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TipoMetodologia", "DuracionMin", "PenetracionRango")
                        .HasDatabaseName("IX_EqParamPrecio_TipoMetodologia_Duracion_Penetracion");

                    b.ToTable("eq_param_precio");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqParamScriptProc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionMin")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HorasGraficacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasHarmoni")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasProc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasScript")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DuracionMin")
                        .HasDatabaseName("IX_EqParamScriptProc_DuracionMin");

                    b.ToTable("eq_param_script_proc");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqQuestionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ASCII")
                        .HasColumnType("bit");

                    b.Property<string>("ClasePrueba")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Codificacion")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CompraProducto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DataCleaning")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("Embalaje")
                        .HasColumnType("bit");

                    b.Property<string>("EtiquetadoTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("NumProcesamientos")
                        .HasColumnType("int");

                    b.Property<string>("OtrosProcesos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatinadoresPorCiudad")
                        .HasColumnType("int");

                    b.Property<string>("PenetracionLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PenetracionValor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PreguntasAbiertas")
                        .HasColumnType("int");

                    b.Property<int>("PreguntasAbiertasMultiples")
                        .HasColumnType("int");

                    b.Property<bool>("Procesamiento")
                        .HasColumnType("bit");

                    b.Property<bool>("ProcesoEstadistico")
                        .HasColumnType("bit");

                    b.Property<int>("ProductosATestear")
                        .HasColumnType("int");

                    b.Property<int>("ProductosPorRespondiente")
                        .HasColumnType("int");

                    b.Property<int>("QuoteHeaderId")
                        .HasColumnType("int");

                    b.Property<bool>("Refrigeracion")
                        .HasColumnType("bit");

                    b.Property<bool>("ScriptReclutamiento")
                        .HasColumnType("bit");

                    b.Property<bool>("Scripting")
                        .HasColumnType("bit");

                    b.Property<bool>("Siembra")
                        .HasColumnType("bit");

                    b.Property<string>("TipoScript")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TopLine")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("QuoteHeaderId")
                        .HasDatabaseName("IX_EqQuestionnaire_QuoteHeaderId");

                    b.ToTable("eq_questionnaire");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqQuoteHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FechaAprobacionEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCampo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GrupoObjetivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetodologiaSL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProbabilidadAprobacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PropuestaNombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecordDetail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ValorGMU")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorProveedorExterno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorProveedorInternacional")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cliente")
                        .HasDatabaseName("IX_EqQuoteHeader_Cliente");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_EqQuoteHeader_FechaCreacion");

                    b.ToTable("eq_quote_header");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqRateEstadistica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ejemplos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("FactorEconomiaEscala")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FactorEscala")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HorasEstimadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LeadTime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioRef2024")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_EqRateEstadistica_Categoria");

                    b.ToTable("eq_rate_estadistica");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqSampleCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EnvioCiudades")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("MetodologiaTecnicaReferenciada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MuestraTotal")
                        .HasColumnType("int");

                    b.Property<int>("NSE1")
                        .HasColumnType("int");

                    b.Property<int>("NSE2")
                        .HasColumnType("int");

                    b.Property<int>("NSE3")
                        .HasColumnType("int");

                    b.Property<int>("NSE4")
                        .HasColumnType("int");

                    b.Property<int>("NSE5")
                        .HasColumnType("int");

                    b.Property<int>("NSE6")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoProductoGramos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuoteHeaderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SobreMuestraPct")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Ciudad")
                        .HasDatabaseName("IX_EqSampleCity_Ciudad");

                    b.HasIndex("QuoteHeaderId")
                        .HasDatabaseName("IX_EqSampleCity_QuoteHeaderId");

                    b.ToTable("eq_sample_city");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqStaffSL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("HorasMinimas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasPresupuestadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("QuoteHeaderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifaNivel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteHeaderId")
                        .HasDatabaseName("IX_EqStaffSL_QuoteHeaderId");

                    b.ToTable("eq_staff_sl");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqValorHoraOps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alternativa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BaseCostRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BillingRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LoadedCostRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("OverheadRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VigentDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VigentHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nivel", "Alternativa")
                        .HasDatabaseName("IX_EqValorHoraOps_Nivel_Alternativa");

                    b.ToTable("eq_valor_hora_ops");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.AsignacionProyecto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdGerentePrevio")
                        .HasColumnType("bigint");

                    b.Property<long>("IdGerenteProyecto")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProyecto")
                        .HasColumnType("bigint");

                    b.Property<string>("NombreGerentePrevio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreGerenteProyecto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAsignacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdProyecto");

                    b.ToTable("PY_AsignacionProyectos", "dbo");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.EntrevistadorasCuali", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Disponibilidad")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Disponible");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Asignado");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTermino")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdSegmento")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTrabajoCuali")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint");

                    b.Property<string>("NivelExperiencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEntrevistasAsignadas")
                        .HasColumnType("int");

                    b.Property<int>("NumeroEntrevistasCompletadas")
                        .HasColumnType("int");

                    b.Property<decimal?>("PorcentajeCumplimiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("TrabajoCualiId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_EntrevistadorasCuali_Estado");

                    b.HasIndex("IdSegmento");

                    b.HasIndex("IdTrabajoCuali")
                        .HasDatabaseName("IX_EntrevistadorasCuali_IdTrabajoCuali");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("IX_EntrevistadorasCuali_IdUsuario");

                    b.HasIndex("TrabajoCualiId");

                    b.ToTable("EntrevistadorasCuali");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.MuestrasCuali", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CalidadDatos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DuracionEntrevista")
                        .HasColumnType("int");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Planeada");

                    b.Property<int?>("Estrato")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaContacto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("IdEntrevistador")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdSegmento")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdSesion")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTrabajoCuali")
                        .HasColumnType("bigint");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreParticipante")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroMuestra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ocupacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("SesionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_MuestrasCuali_Estado");

                    b.HasIndex("IdEntrevistador")
                        .HasDatabaseName("IX_MuestrasCuali_IdEntrevistador");

                    b.HasIndex("IdSegmento");

                    b.HasIndex("IdTrabajoCuali")
                        .HasDatabaseName("IX_MuestrasCuali_IdTrabajoCuali");

                    b.HasIndex("NumeroMuestra")
                        .HasDatabaseName("IX_MuestrasCuali_NumeroMuestra");

                    b.HasIndex("SesionId");

                    b.ToTable("MuestrasCuali");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.ParticipantesSesion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Asistencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CalidadRespuestas")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdMuestra")
                        .HasColumnType("bigint");

                    b.Property<long>("IdSesion")
                        .HasColumnType("bigint");

                    b.Property<string>("MotivoInasistencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MuestraId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Asistencia")
                        .HasDatabaseName("IX_ParticipantesSesion_Asistencia");

                    b.HasIndex("IdMuestra")
                        .HasDatabaseName("IX_ParticipantesSesion_IdMuestra");

                    b.HasIndex("IdSesion")
                        .HasDatabaseName("IX_ParticipantesSesion_IdSesion");

                    b.HasIndex("MuestraId");

                    b.ToTable("ParticipantesSesion");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.Proyecto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("IdGerenteProyectos")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUnidad")
                        .HasColumnType("bigint");

                    b.Property<string>("JobBook")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Proyecto_Activo");

                    b.HasIndex("IdGerenteProyectos")
                        .HasDatabaseName("IX_Proyecto_IdGerenteProyectos");

                    b.HasIndex("IdUnidad")
                        .HasDatabaseName("IX_Proyecto_IdUnidad");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.SegmentosCuali", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CriteriosExclusion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CriteriosInclusion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("CuotaMaxima")
                        .HasColumnType("int");

                    b.Property<int?>("CuotaMinima")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdTrabajoCuali")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroParticipantes")
                        .HasColumnType("int");

                    b.Property<int?>("Orden")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_SegmentosCuali_Activo");

                    b.HasIndex("IdTrabajoCuali")
                        .HasDatabaseName("IX_SegmentosCuali_IdTrabajoCuali");

                    b.ToTable("SegmentosCuali");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.SesionesCuali", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("DuracionEstimada")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionReal")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Planeada");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoraFin")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoraInicio")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long?>("IdSegmento")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTrabajoCuali")
                        .HasColumnType("bigint");

                    b.Property<string>("Moderador")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroParticipantesPlaneado")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroParticipantesReal")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SegmentoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UrlGrabacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_SesionesCuali_Estado");

                    b.HasIndex("FechaProgramada")
                        .HasDatabaseName("IX_SesionesCuali_FechaProgramada");

                    b.HasIndex("IdTrabajoCuali")
                        .HasDatabaseName("IX_SesionesCuali_IdTrabajoCuali");

                    b.HasIndex("SegmentoId");

                    b.ToTable("SesionesCuali");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.Trabajo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("IdCoordinador")
                        .HasColumnType("bigint");

                    b.Property<int>("IdMetodologia")
                        .HasColumnType("int");

                    b.Property<long>("IdProyecto")
                        .HasColumnType("bigint");

                    b.Property<int>("IdTipoProyecto")
                        .HasColumnType("int");

                    b.Property<string>("JobBook")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Trabajo_Activo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Trabajo_Estado");

                    b.HasIndex("IdProyecto")
                        .HasDatabaseName("IX_Trabajo_IdProyecto");

                    b.ToTable("Trabajos");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.TrabajosCuali", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Creado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdCoordinador")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdGerenteProyecto")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProyecto")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdTrabajoRelacionado")
                        .HasColumnType("bigint");

                    b.Property<string>("JobBook")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroParticipantesEstimado")
                        .HasColumnType("int");

                    b.Property<decimal?>("PresupuestoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ProyectoId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoEstudio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_TrabajosCuali_Activo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_TrabajosCuali_Estado");

                    b.HasIndex("IdProyecto")
                        .HasDatabaseName("IX_TrabajosCuali_IdProyecto");

                    b.HasIndex("ProyectoId");

                    b.ToTable("TrabajosCuali");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.VariableControl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdTrabajo")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TipoDato")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioModificacion")
                        .HasColumnType("bigint");

                    b.Property<string>("Valor")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IdTrabajo");

                    b.ToTable("VariablesControl");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.CORE.ObservacionTarea", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.CORE.WorkFlow", "WorkFlow")
                        .WithMany("Observaciones_Log")
                        .HasForeignKey("IdWorkFlow")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkFlow");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.CORE.TareaPrevia", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.CORE.WorkFlow", "Tarea")
                        .WithMany("TareasPrevias")
                        .HasForeignKey("IdTarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatrixNext.Web.Models.CORE.WorkFlow", "TareaPreviaRequerida")
                        .WithMany()
                        .HasForeignKey("IdTareaPreviaRequerida")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tarea");

                    b.Navigation("TareaPreviaRequerida");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.CORE.WorkFlowUsuarioAsignado", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.CORE.WorkFlow", "WorkFlow")
                        .WithMany("UsuariosAsignados")
                        .HasForeignKey("IdWorkFlow")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkFlow");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqCostResult", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.EQ.EqQuoteHeader", "QuoteHeader")
                        .WithOne("CostResult")
                        .HasForeignKey("MatrixNext.Web.Models.EQ.EqCostResult", "QuoteHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteHeader");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqMethodology", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.EQ.EqQuoteHeader", "QuoteHeader")
                        .WithMany("Methodologies")
                        .HasForeignKey("QuoteHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteHeader");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqMystery", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.EQ.EqQuoteHeader", "QuoteHeader")
                        .WithMany("Mysteries")
                        .HasForeignKey("QuoteHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteHeader");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqQuestionnaire", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.EQ.EqQuoteHeader", "QuoteHeader")
                        .WithMany("Questionnaires")
                        .HasForeignKey("QuoteHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteHeader");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqSampleCity", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.EQ.EqQuoteHeader", "QuoteHeader")
                        .WithMany("SampleCities")
                        .HasForeignKey("QuoteHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteHeader");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqStaffSL", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.EQ.EqQuoteHeader", "QuoteHeader")
                        .WithMany("StaffSL")
                        .HasForeignKey("QuoteHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteHeader");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.AsignacionProyecto", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.PY.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.EntrevistadorasCuali", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.PY.SegmentosCuali", "Segmento")
                        .WithMany("Entrevistadores")
                        .HasForeignKey("IdSegmento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MatrixNext.Web.Models.PY.TrabajosCuali", "TrabajoCuali")
                        .WithMany()
                        .HasForeignKey("TrabajoCualiId");

                    b.Navigation("Segmento");

                    b.Navigation("TrabajoCuali");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.MuestrasCuali", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.PY.EntrevistadorasCuali", "Entrevistador")
                        .WithMany("Muestras")
                        .HasForeignKey("IdEntrevistador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MatrixNext.Web.Models.PY.SegmentosCuali", "Segmento")
                        .WithMany("Muestras")
                        .HasForeignKey("IdSegmento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MatrixNext.Web.Models.PY.TrabajosCuali", "TrabajoCuali")
                        .WithMany("Muestras")
                        .HasForeignKey("IdTrabajoCuali")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MatrixNext.Web.Models.PY.SesionesCuali", "Sesion")
                        .WithMany()
                        .HasForeignKey("SesionId");

                    b.Navigation("Entrevistador");

                    b.Navigation("Segmento");

                    b.Navigation("Sesion");

                    b.Navigation("TrabajoCuali");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.ParticipantesSesion", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.PY.SesionesCuali", "Sesion")
                        .WithMany("Participantes")
                        .HasForeignKey("IdSesion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatrixNext.Web.Models.PY.MuestrasCuali", "Muestra")
                        .WithMany()
                        .HasForeignKey("MuestraId");

                    b.Navigation("Muestra");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.SegmentosCuali", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.PY.TrabajosCuali", "TrabajoCuali")
                        .WithMany("Segmentos")
                        .HasForeignKey("IdTrabajoCuali")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrabajoCuali");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.SesionesCuali", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.PY.TrabajosCuali", "TrabajoCuali")
                        .WithMany("Sesiones")
                        .HasForeignKey("IdTrabajoCuali")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatrixNext.Web.Models.PY.SegmentosCuali", "Segmento")
                        .WithMany()
                        .HasForeignKey("SegmentoId");

                    b.Navigation("Segmento");

                    b.Navigation("TrabajoCuali");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.Trabajo", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.PY.Proyecto", "Proyecto")
                        .WithMany("Trabajos")
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.TrabajosCuali", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.PY.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.VariableControl", b =>
                {
                    b.HasOne("MatrixNext.Web.Models.PY.Trabajo", "Trabajo")
                        .WithMany("VariablesControl")
                        .HasForeignKey("IdTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.CORE.WorkFlow", b =>
                {
                    b.Navigation("Observaciones_Log");

                    b.Navigation("TareasPrevias");

                    b.Navigation("UsuariosAsignados");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.EQ.EqQuoteHeader", b =>
                {
                    b.Navigation("CostResult")
                        .IsRequired();

                    b.Navigation("Methodologies");

                    b.Navigation("Mysteries");

                    b.Navigation("Questionnaires");

                    b.Navigation("SampleCities");

                    b.Navigation("StaffSL");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.EntrevistadorasCuali", b =>
                {
                    b.Navigation("Muestras");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.Proyecto", b =>
                {
                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.SegmentosCuali", b =>
                {
                    b.Navigation("Entrevistadores");

                    b.Navigation("Muestras");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.SesionesCuali", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.Trabajo", b =>
                {
                    b.Navigation("VariablesControl");
                });

            modelBuilder.Entity("MatrixNext.Web.Models.PY.TrabajosCuali", b =>
                {
                    b.Navigation("Muestras");

                    b.Navigation("Segmentos");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
