'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProductoNoConformeRegistrar

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hfId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Filtro1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filtro1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rdTrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdTrabajo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdEstudio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdEstudio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblJobBook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobBook As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NEstudio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NEstudio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''GVTrabajos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVTrabajos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GVPNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPNC As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GVPNCCausas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPNCCausas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GVPNCAcciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPNCAcciones As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Filtro2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Filtro2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''JobBook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobBook As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''IdTrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IdTrabajo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NomTrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NomTrabajo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Unidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Unidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Datos1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Datos1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Reporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reporta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Cliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FechaReclamo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FechaReclamo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Fuente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fuente As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Categoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Categoria As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Tarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tarea As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Datos2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Datos2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGrabarPNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabarPNC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtCausa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCausa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGrabarCausa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabarCausa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TipoAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TipoAccion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ResponsableAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResponsableAccion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ResponsableSeguir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResponsableSeguir As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''FechaPlanAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FechaPlanAccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FechaEjecAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FechaEjecAccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEvidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEvidencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Datos3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Datos3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnGrabarAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabarAccion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnActualizarFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnActualizarFecha As Global.System.Web.UI.WebControls.Button
End Class
