'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class C_Divipola3
    Public Property DivDeptoMunicipio As Integer
    Public Property DivDepto As Short
    Public Property DivMunicipio As Integer
    Public Property DivDeptoNombre As String
    Public Property DivMuniNombre As String
    Public Property DivOrden As Nullable(Of Short)
    Public Property Pais As Nullable(Of Integer)
    Public Property Agrupacion As Nullable(Of Integer)
    Public Property Agrupacion2 As Nullable(Of Integer)
    Public Property Agrupacion3 As Nullable(Of Integer)

End Class
