'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CC_CargosActividades
    Public Property Id As Integer
    Public Property Año As Integer
    Public Property IdTipoCargo As Long
    Public Property Descripcion As String
    Public Property TipoPresupuesto As String
    Public Property CargoId As Nullable(Of Integer)
    Public Property TipoVinculacion As Nullable(Of Byte)
    Public Property Valor As Nullable(Of Double)
    Public Property PCesantias As Nullable(Of Double)
    Public Property PIntCesantias As Nullable(Of Double)
    Public Property PVacaciones As Nullable(Of Double)
    Public Property PPrimaLegal As Nullable(Of Double)
    Public Property SaludDto As Nullable(Of Double)
    Public Property SaludCosto As Nullable(Of Double)
    Public Property PensionDto As Nullable(Of Double)
    Public Property PensionCosto As Nullable(Of Double)
    Public Property ARLDto As Nullable(Of Double)
    Public Property ARLCosto As Nullable(Of Double)
    Public Property CCFDto As Nullable(Of Double)
    Public Property CCFCosto As Nullable(Of Double)
    Public Property Otro1Dto As Nullable(Of Double)
    Public Property Otro1Costo As Nullable(Of Double)
    Public Property Otro2Dto As Nullable(Of Double)
    Public Property Otro2Costo As Nullable(Of Double)
    Public Property RetencionMayorA As Nullable(Of Double)
    Public Property RetencionDto As Nullable(Of Double)
    Public Property FactorAjusteValor As Nullable(Of Double)
    Public Property FactorSupervision As Nullable(Of Double)
    Public Property BaseCotizacion As Nullable(Of Double)

End Class
