'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CC_TiposDePresupuesto
    Public Property TipoPresupuesto As Integer
    Public Property Descripcion As String
    Public Property EncxSupervisor As Nullable(Of Integer)
    Public Property SupxCoordinador As Nullable(Of Integer)

End Class
