'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class CORE_Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CORE_Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CORE_WorkflowEstados() As DbSet(Of CORE_WorkflowEstados)
    Public Overridable Property CORE_Retroalimentacion() As DbSet(Of CORE_Retroalimentacion)
    Public Overridable Property CORE_TipoRetroalimentacion() As DbSet(Of CORE_TipoRetroalimentacion)
    Public Overridable Property US_Usuarios() As DbSet(Of US_Usuarios3)
    Public Overridable Property CORE_Hilos() As DbSet(Of CORE_Hilos)
    Public Overridable Property CORE_Tareas_Documentos() As DbSet(Of CORE_Tareas_Documentos)
    Public Overridable Property CORE_TareasPrevias() As DbSet(Of CORE_TareasPrevias)
    Public Overridable Property CORE_Tareas() As DbSet(Of CORE_Tareas)
    Public Overridable Property CORE_TipoHilo_Tareas() As DbSet(Of CORE_TipoHilo_Tareas)
    Public Overridable Property CORE_TipoHilos() As DbSet(Of CORE_TipoHilos)
    Public Overridable Property CORE_Unidades() As DbSet(Of CORE_Unidades)
    Public Overridable Property CORE_WorkFlow_UsuariosAsignados() As DbSet(Of CORE_WorkFlow_UsuariosAsignados)
    Public Overridable Property US_RolesUsuarios2() As DbSet(Of US_RolesUsuarios2)
    Public Overridable Property CORE_Planeacion() As DbSet(Of CORE_Planeacion)
    Public Overridable Property CORE_WorkFlow() As DbSet(Of CORE_WorkFlow)

    Public Overridable Function CORE_DocumentosRequeridosXTarea_Get(tareaId As Nullable(Of Long), tipoDocumentoTareaId As Nullable(Of Short), idContenedor As Nullable(Of Long)) As ObjectResult(Of CORE_DocumentosRequeridosXTarea_Get_Result)
        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("TareaId", tareaId), New ObjectParameter("TareaId", GetType(Long)))

        Dim tipoDocumentoTareaIdParameter As ObjectParameter = If(tipoDocumentoTareaId.HasValue, New ObjectParameter("TipoDocumentoTareaId", tipoDocumentoTareaId), New ObjectParameter("TipoDocumentoTareaId", GetType(Short)))

        Dim idContenedorParameter As ObjectParameter = If(idContenedor.HasValue, New ObjectParameter("IdContenedor", idContenedor), New ObjectParameter("IdContenedor", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_DocumentosRequeridosXTarea_Get_Result)("CORE_DocumentosRequeridosXTarea_Get", tareaIdParameter, tipoDocumentoTareaIdParameter, idContenedorParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_Trabajos_Get(id As Nullable(Of Long), hiloId As Nullable(Of Long), tareaId As Nullable(Of Long), fIniP As Nullable(Of Date), fFinP As Nullable(Of Date), fIniR As Nullable(Of Date), fFinR As Nullable(Of Date), usuarioEstima As Nullable(Of Long), usuarioAsignado As Nullable(Of Long), trabajoId As Nullable(Of Long), todosCampos As String, rolEstima As Nullable(Of Integer), estadoWorkFlow_Id As Nullable(Of Short), unidadEjecuta As Nullable(Of Long)) As ObjectResult(Of CORE_WorkFlow_Trabajos_Get_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Dim hiloIdParameter As ObjectParameter = If(hiloId.HasValue, New ObjectParameter("HiloId", hiloId), New ObjectParameter("HiloId", GetType(Long)))

        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("TareaId", tareaId), New ObjectParameter("TareaId", GetType(Long)))

        Dim fIniPParameter As ObjectParameter = If(fIniP.HasValue, New ObjectParameter("FIniP", fIniP), New ObjectParameter("FIniP", GetType(Date)))

        Dim fFinPParameter As ObjectParameter = If(fFinP.HasValue, New ObjectParameter("FFinP", fFinP), New ObjectParameter("FFinP", GetType(Date)))

        Dim fIniRParameter As ObjectParameter = If(fIniR.HasValue, New ObjectParameter("FIniR", fIniR), New ObjectParameter("FIniR", GetType(Date)))

        Dim fFinRParameter As ObjectParameter = If(fFinR.HasValue, New ObjectParameter("FFinR", fFinR), New ObjectParameter("FFinR", GetType(Date)))

        Dim usuarioEstimaParameter As ObjectParameter = If(usuarioEstima.HasValue, New ObjectParameter("UsuarioEstima", usuarioEstima), New ObjectParameter("UsuarioEstima", GetType(Long)))

        Dim usuarioAsignadoParameter As ObjectParameter = If(usuarioAsignado.HasValue, New ObjectParameter("UsuarioAsignado", usuarioAsignado), New ObjectParameter("UsuarioAsignado", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim todosCamposParameter As ObjectParameter = If(todosCampos IsNot Nothing, New ObjectParameter("TodosCampos", todosCampos), New ObjectParameter("TodosCampos", GetType(String)))

        Dim rolEstimaParameter As ObjectParameter = If(rolEstima.HasValue, New ObjectParameter("RolEstima", rolEstima), New ObjectParameter("RolEstima", GetType(Integer)))

        Dim estadoWorkFlow_IdParameter As ObjectParameter = If(estadoWorkFlow_Id.HasValue, New ObjectParameter("EstadoWorkFlow_Id", estadoWorkFlow_Id), New ObjectParameter("EstadoWorkFlow_Id", GetType(Short)))

        Dim unidadEjecutaParameter As ObjectParameter = If(unidadEjecuta.HasValue, New ObjectParameter("unidadEjecuta", unidadEjecuta), New ObjectParameter("unidadEjecuta", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_WorkFlow_Trabajos_Get_Result)("CORE_WorkFlow_Trabajos_Get", idParameter, hiloIdParameter, tareaIdParameter, fIniPParameter, fFinPParameter, fIniRParameter, fFinRParameter, usuarioEstimaParameter, usuarioAsignadoParameter, trabajoIdParameter, todosCamposParameter, rolEstimaParameter, estadoWorkFlow_IdParameter, unidadEjecutaParameter)
    End Function

    Public Overridable Function CORE_Hilo_Add(tipoHiloId As Nullable(Of Long), contenedorId As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Decimal))
        Dim tipoHiloIdParameter As ObjectParameter = If(tipoHiloId.HasValue, New ObjectParameter("TipoHiloId", tipoHiloId), New ObjectParameter("TipoHiloId", GetType(Long)))

        Dim contenedorIdParameter As ObjectParameter = If(contenedorId.HasValue, New ObjectParameter("ContenedorId", contenedorId), New ObjectParameter("ContenedorId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Decimal))("CORE_Hilo_Add", tipoHiloIdParameter, contenedorIdParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_Add(hiloId As Nullable(Of Long)) As Integer
        Dim hiloIdParameter As ObjectParameter = If(hiloId.HasValue, New ObjectParameter("HiloId", hiloId), New ObjectParameter("HiloId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CORE_WorkFlow_Add", hiloIdParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_Edit(id As Nullable(Of Long), fIniP As Nullable(Of Date), fFinP As Nullable(Of Date), fIniR As Nullable(Of Date), fFinR As Nullable(Of Date), usuarioEstima As Nullable(Of Long), usuarioAsignado As Nullable(Of Long), observacionesPlaneacion As String) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Long)))

        Dim fIniPParameter As ObjectParameter = If(fIniP.HasValue, New ObjectParameter("FIniP", fIniP), New ObjectParameter("FIniP", GetType(Date)))

        Dim fFinPParameter As ObjectParameter = If(fFinP.HasValue, New ObjectParameter("FFinP", fFinP), New ObjectParameter("FFinP", GetType(Date)))

        Dim fIniRParameter As ObjectParameter = If(fIniR.HasValue, New ObjectParameter("FIniR", fIniR), New ObjectParameter("FIniR", GetType(Date)))

        Dim fFinRParameter As ObjectParameter = If(fFinR.HasValue, New ObjectParameter("FFinR", fFinR), New ObjectParameter("FFinR", GetType(Date)))

        Dim usuarioEstimaParameter As ObjectParameter = If(usuarioEstima.HasValue, New ObjectParameter("UsuarioEstima", usuarioEstima), New ObjectParameter("UsuarioEstima", GetType(Long)))

        Dim usuarioAsignadoParameter As ObjectParameter = If(usuarioAsignado.HasValue, New ObjectParameter("UsuarioAsignado", usuarioAsignado), New ObjectParameter("UsuarioAsignado", GetType(Long)))

        Dim observacionesPlaneacionParameter As ObjectParameter = If(observacionesPlaneacion IsNot Nothing, New ObjectParameter("ObservacionesPlaneacion", observacionesPlaneacion), New ObjectParameter("ObservacionesPlaneacion", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CORE_WorkFlow_Edit", idParameter, fIniPParameter, fFinPParameter, fIniRParameter, fFinRParameter, usuarioEstimaParameter, usuarioAsignadoParameter, observacionesPlaneacionParameter)
    End Function

    Public Overridable Function CORE_Tareas_Get(id As Nullable(Of Long)) As ObjectResult(Of CORE_Tareas_Get_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_Tareas_Get_Result)("CORE_Tareas_Get", idParameter)
    End Function

    Public Overridable Function CORE_Planeacion_Add(core_WorkFlow_Id As Nullable(Of Long), fechaInicio As Nullable(Of Date), fechaFin As Nullable(Of Date), usuario As Nullable(Of Long), fechaRegistro As Nullable(Of Date), observacion As String) As ObjectResult(Of Nullable(Of Decimal))
        Dim core_WorkFlow_IdParameter As ObjectParameter = If(core_WorkFlow_Id.HasValue, New ObjectParameter("Core_WorkFlow_Id", core_WorkFlow_Id), New ObjectParameter("Core_WorkFlow_Id", GetType(Long)))

        Dim fechaInicioParameter As ObjectParameter = If(fechaInicio.HasValue, New ObjectParameter("FechaInicio", fechaInicio), New ObjectParameter("FechaInicio", GetType(Date)))

        Dim fechaFinParameter As ObjectParameter = If(fechaFin.HasValue, New ObjectParameter("FechaFin", fechaFin), New ObjectParameter("FechaFin", GetType(Date)))

        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(Long)))

        Dim fechaRegistroParameter As ObjectParameter = If(fechaRegistro.HasValue, New ObjectParameter("FechaRegistro", fechaRegistro), New ObjectParameter("FechaRegistro", GetType(Date)))

        Dim observacionParameter As ObjectParameter = If(observacion IsNot Nothing, New ObjectParameter("Observacion", observacion), New ObjectParameter("Observacion", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Decimal))("CORE_Planeacion_Add", core_WorkFlow_IdParameter, fechaInicioParameter, fechaFinParameter, usuarioParameter, fechaRegistroParameter, observacionParameter)
    End Function

    Public Overridable Function CORE_Log_WorkFlow_MasivoEstadoCreada_Add(trabajoId As Nullable(Of Long), fechaRegistro As Nullable(Of Date), usuario As Nullable(Of Long), tipohiloId As Nullable(Of Long)) As Integer
        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim fechaRegistroParameter As ObjectParameter = If(fechaRegistro.HasValue, New ObjectParameter("FechaRegistro", fechaRegistro), New ObjectParameter("FechaRegistro", GetType(Date)))

        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(Long)))

        Dim tipohiloIdParameter As ObjectParameter = If(tipohiloId.HasValue, New ObjectParameter("tipohiloId", tipohiloId), New ObjectParameter("tipohiloId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CORE_Log_WorkFlow_MasivoEstadoCreada_Add", trabajoIdParameter, fechaRegistroParameter, usuarioParameter, tipohiloIdParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_TareasPrevias_Get(tipoHiloId As Nullable(Of Long), tareaId As Nullable(Of Long), trabajoId As Nullable(Of Long)) As ObjectResult(Of CORE_WorkFlow_TareasPrevias_Get_Result)
        Dim tipoHiloIdParameter As ObjectParameter = If(tipoHiloId.HasValue, New ObjectParameter("TipoHiloId", tipoHiloId), New ObjectParameter("TipoHiloId", GetType(Long)))

        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("TareaId", tareaId), New ObjectParameter("TareaId", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("trabajoId", trabajoId), New ObjectParameter("trabajoId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_WorkFlow_TareasPrevias_Get_Result)("CORE_WorkFlow_TareasPrevias_Get", tipoHiloIdParameter, tareaIdParameter, trabajoIdParameter)
    End Function

    Public Overridable Function CORE_Log_WorkFlow_Add(core_WorkFlow_Id As Nullable(Of Long), fechaRegistro As Nullable(Of Date), usuario As Nullable(Of Long), estadoWorkFlow_Id As Nullable(Of Short), observacion As String) As ObjectResult(Of Nullable(Of Decimal))
        Dim core_WorkFlow_IdParameter As ObjectParameter = If(core_WorkFlow_Id.HasValue, New ObjectParameter("core_WorkFlow_Id", core_WorkFlow_Id), New ObjectParameter("core_WorkFlow_Id", GetType(Long)))

        Dim fechaRegistroParameter As ObjectParameter = If(fechaRegistro.HasValue, New ObjectParameter("fechaRegistro", fechaRegistro), New ObjectParameter("fechaRegistro", GetType(Date)))

        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(Long)))

        Dim estadoWorkFlow_IdParameter As ObjectParameter = If(estadoWorkFlow_Id.HasValue, New ObjectParameter("EstadoWorkFlow_Id", estadoWorkFlow_Id), New ObjectParameter("EstadoWorkFlow_Id", GetType(Short)))

        Dim observacionParameter As ObjectParameter = If(observacion IsNot Nothing, New ObjectParameter("observacion", observacion), New ObjectParameter("observacion", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Decimal))("CORE_Log_WorkFlow_Add", core_WorkFlow_IdParameter, fechaRegistroParameter, usuarioParameter, estadoWorkFlow_IdParameter, observacionParameter)
    End Function

    Public Overridable Function Divipola_Get(pais As Nullable(Of Integer)) As ObjectResult(Of Divipola_Get_Result)
        Dim paisParameter As ObjectParameter = If(pais.HasValue, New ObjectParameter("Pais", pais), New ObjectParameter("Pais", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Divipola_Get_Result)("Divipola_Get", paisParameter)
    End Function

    Public Overridable Function CORE_Trabajos_WithWorkFlow(id As Nullable(Of Long), hiloId As Nullable(Of Long), tareaId As Nullable(Of Long), fIniP As Nullable(Of Date), fFinP As Nullable(Of Date), fIniR As Nullable(Of Date), fFinR As Nullable(Of Date), usuarioEstima As Nullable(Of Long), usuarioAsignado As Nullable(Of Long), trabajoId As Nullable(Of Long), todosCampos As String, rolEstima As Nullable(Of Integer), estadoWorkFlow_Id As Nullable(Of Short), unidadEjecuta As Nullable(Of Long)) As ObjectResult(Of CORE_Trabajos_WithWorkFlow_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Dim hiloIdParameter As ObjectParameter = If(hiloId.HasValue, New ObjectParameter("HiloId", hiloId), New ObjectParameter("HiloId", GetType(Long)))

        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("TareaId", tareaId), New ObjectParameter("TareaId", GetType(Long)))

        Dim fIniPParameter As ObjectParameter = If(fIniP.HasValue, New ObjectParameter("FIniP", fIniP), New ObjectParameter("FIniP", GetType(Date)))

        Dim fFinPParameter As ObjectParameter = If(fFinP.HasValue, New ObjectParameter("FFinP", fFinP), New ObjectParameter("FFinP", GetType(Date)))

        Dim fIniRParameter As ObjectParameter = If(fIniR.HasValue, New ObjectParameter("FIniR", fIniR), New ObjectParameter("FIniR", GetType(Date)))

        Dim fFinRParameter As ObjectParameter = If(fFinR.HasValue, New ObjectParameter("FFinR", fFinR), New ObjectParameter("FFinR", GetType(Date)))

        Dim usuarioEstimaParameter As ObjectParameter = If(usuarioEstima.HasValue, New ObjectParameter("UsuarioEstima", usuarioEstima), New ObjectParameter("UsuarioEstima", GetType(Long)))

        Dim usuarioAsignadoParameter As ObjectParameter = If(usuarioAsignado.HasValue, New ObjectParameter("UsuarioAsignado", usuarioAsignado), New ObjectParameter("UsuarioAsignado", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim todosCamposParameter As ObjectParameter = If(todosCampos IsNot Nothing, New ObjectParameter("TodosCampos", todosCampos), New ObjectParameter("TodosCampos", GetType(String)))

        Dim rolEstimaParameter As ObjectParameter = If(rolEstima.HasValue, New ObjectParameter("RolEstima", rolEstima), New ObjectParameter("RolEstima", GetType(Integer)))

        Dim estadoWorkFlow_IdParameter As ObjectParameter = If(estadoWorkFlow_Id.HasValue, New ObjectParameter("EstadoWorkFlow_Id", estadoWorkFlow_Id), New ObjectParameter("EstadoWorkFlow_Id", GetType(Short)))

        Dim unidadEjecutaParameter As ObjectParameter = If(unidadEjecuta.HasValue, New ObjectParameter("unidadEjecuta", unidadEjecuta), New ObjectParameter("unidadEjecuta", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_Trabajos_WithWorkFlow_Result)("CORE_Trabajos_WithWorkFlow", idParameter, hiloIdParameter, tareaIdParameter, fIniPParameter, fFinPParameter, fIniRParameter, fFinRParameter, usuarioEstimaParameter, usuarioAsignadoParameter, trabajoIdParameter, todosCamposParameter, rolEstimaParameter, estadoWorkFlow_IdParameter, unidadEjecutaParameter)
    End Function

    Public Overridable Function CORE_obtenerCantidadTareasXTrabajo(idUsuario As Nullable(Of Long)) As ObjectResult(Of CORE_obtenerCantidadTareasXTrabajo_Result)
        Dim idUsuarioParameter As ObjectParameter = If(idUsuario.HasValue, New ObjectParameter("idUsuario", idUsuario), New ObjectParameter("idUsuario", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_obtenerCantidadTareasXTrabajo_Result)("CORE_obtenerCantidadTareasXTrabajo", idUsuarioParameter)
    End Function

    Public Overridable Function CORE_Asunto_Get() As ObjectResult(Of CORE_Asunto_Get_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_Asunto_Get_Result)("CORE_Asunto_Get")
    End Function

    Public Overridable Function CORE_Feedback_Add(usuario As Nullable(Of Long), tipoId As Nullable(Of Integer), mensaje As String) As ObjectResult(Of Nullable(Of Long))
        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(Long)))

        Dim tipoIdParameter As ObjectParameter = If(tipoId.HasValue, New ObjectParameter("TipoId", tipoId), New ObjectParameter("TipoId", GetType(Integer)))

        Dim mensajeParameter As ObjectParameter = If(mensaje IsNot Nothing, New ObjectParameter("Mensaje", mensaje), New ObjectParameter("Mensaje", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Long))("CORE_Feedback_Add", usuarioParameter, tipoIdParameter, mensajeParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_TareasAsociadas_Get(trabajoId As Nullable(Of Long), tareaId As Nullable(Of Long)) As ObjectResult(Of CORE_WorkFlow_TareasAsociadas_Get_Result)
        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("trabajoId", trabajoId), New ObjectParameter("trabajoId", GetType(Long)))

        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("tareaId", tareaId), New ObjectParameter("tareaId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_WorkFlow_TareasAsociadas_Get_Result)("CORE_WorkFlow_TareasAsociadas_Get", trabajoIdParameter, tareaIdParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_UsuariosANotificarTareaDevuelta_Get(trabajoId As Nullable(Of Long), tareaId As Nullable(Of Long)) As ObjectResult(Of CORE_WorkFlow_UsuariosANotificarTareaDevuelta_Get_Result)
        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("trabajoId", trabajoId), New ObjectParameter("trabajoId", GetType(Long)))

        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("tareaId", tareaId), New ObjectParameter("tareaId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_WorkFlow_UsuariosANotificarTareaDevuelta_Get_Result)("CORE_WorkFlow_UsuariosANotificarTareaDevuelta_Get", trabajoIdParameter, tareaIdParameter)
    End Function

    Public Overridable Function LogEjecucionAdd(fromId As Nullable(Of Integer), idDoc As Nullable(Of Long), fecha As Nullable(Of Date), usuarioId As Nullable(Of Long), accionId As Nullable(Of Byte)) As Integer
        Dim fromIdParameter As ObjectParameter = If(fromId.HasValue, New ObjectParameter("FromId", fromId), New ObjectParameter("FromId", GetType(Integer)))

        Dim idDocParameter As ObjectParameter = If(idDoc.HasValue, New ObjectParameter("idDoc", idDoc), New ObjectParameter("idDoc", GetType(Long)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim usuarioIdParameter As ObjectParameter = If(usuarioId.HasValue, New ObjectParameter("UsuarioId", usuarioId), New ObjectParameter("UsuarioId", GetType(Long)))

        Dim accionIdParameter As ObjectParameter = If(accionId.HasValue, New ObjectParameter("AccionId", accionId), New ObjectParameter("AccionId", GetType(Byte)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("LogEjecucionAdd", fromIdParameter, idDocParameter, fechaParameter, usuarioIdParameter, accionIdParameter)
    End Function

    Public Overridable Function CORE_TareasDependientes_Finalizar(tareaId As Nullable(Of Long), trabajoId As Nullable(Of Long), usuarioId As Nullable(Of Long)) As Integer
        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("tareaId", tareaId), New ObjectParameter("tareaId", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("trabajoId", trabajoId), New ObjectParameter("trabajoId", GetType(Long)))

        Dim usuarioIdParameter As ObjectParameter = If(usuarioId.HasValue, New ObjectParameter("usuarioId", usuarioId), New ObjectParameter("usuarioId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CORE_TareasDependientes_Finalizar", tareaIdParameter, trabajoIdParameter, usuarioIdParameter)
    End Function

    Public Overridable Function CORE_Configuracion_DocumentosXTarea_Get(tareaId As Nullable(Of Long), tipoDocumentoTareaId As Nullable(Of Short), asignado As Nullable(Of Boolean)) As ObjectResult(Of CORE_Configuracion_DocumentosXTarea_Get_Result)
        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("TareaId", tareaId), New ObjectParameter("TareaId", GetType(Long)))

        Dim tipoDocumentoTareaIdParameter As ObjectParameter = If(tipoDocumentoTareaId.HasValue, New ObjectParameter("TipoDocumentoTareaId", tipoDocumentoTareaId), New ObjectParameter("TipoDocumentoTareaId", GetType(Short)))

        Dim asignadoParameter As ObjectParameter = If(asignado.HasValue, New ObjectParameter("Asignado", asignado), New ObjectParameter("Asignado", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_Configuracion_DocumentosXTarea_Get_Result)("CORE_Configuracion_DocumentosXTarea_Get", tareaIdParameter, tipoDocumentoTareaIdParameter, asignadoParameter)
    End Function

    Public Overridable Function CORE_Configuracion_Tareas_Previas(tareaId As Nullable(Of Long), tipoHiloId As Nullable(Of Long), asignada As Nullable(Of Boolean)) As ObjectResult(Of CORE_Configuracion_Tareas_Previas_Result)
        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("TareaId", tareaId), New ObjectParameter("TareaId", GetType(Long)))

        Dim tipoHiloIdParameter As ObjectParameter = If(tipoHiloId.HasValue, New ObjectParameter("TipoHiloId", tipoHiloId), New ObjectParameter("TipoHiloId", GetType(Long)))

        Dim asignadaParameter As ObjectParameter = If(asignada.HasValue, New ObjectParameter("Asignada", asignada), New ObjectParameter("Asignada", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_Configuracion_Tareas_Previas_Result)("CORE_Configuracion_Tareas_Previas", tareaIdParameter, tipoHiloIdParameter, asignadaParameter)
    End Function

    Public Overridable Function CORE_Configuracion_TareasXTipoHilo_Get(tipoHiloId As Nullable(Of Long), asignada As Nullable(Of Boolean)) As ObjectResult(Of CORE_Configuracion_TareasXTipoHilo_Get_Result)
        Dim tipoHiloIdParameter As ObjectParameter = If(tipoHiloId.HasValue, New ObjectParameter("TipoHiloId", tipoHiloId), New ObjectParameter("TipoHiloId", GetType(Long)))

        Dim asignadaParameter As ObjectParameter = If(asignada.HasValue, New ObjectParameter("Asignada", asignada), New ObjectParameter("Asignada", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_Configuracion_TareasXTipoHilo_Get_Result)("CORE_Configuracion_TareasXTipoHilo_Get", tipoHiloIdParameter, asignadaParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_UsuariosAsignados_Get(workFlowId As Nullable(Of Long), asignado As Nullable(Of Boolean), rolId As Nullable(Of Long)) As ObjectResult(Of CORE_WorkFlow_UsuariosAsignados_Get_Result)
        Dim workFlowIdParameter As ObjectParameter = If(workFlowId.HasValue, New ObjectParameter("WorkFlowId", workFlowId), New ObjectParameter("WorkFlowId", GetType(Long)))

        Dim asignadoParameter As ObjectParameter = If(asignado.HasValue, New ObjectParameter("Asignado", asignado), New ObjectParameter("Asignado", GetType(Boolean)))

        Dim rolIdParameter As ObjectParameter = If(rolId.HasValue, New ObjectParameter("RolId", rolId), New ObjectParameter("RolId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_WorkFlow_UsuariosAsignados_Get_Result)("CORE_WorkFlow_UsuariosAsignados_Get", workFlowIdParameter, asignadoParameter, rolIdParameter)
    End Function

    Public Overridable Function CORE_DocumentosXHilo_Get(idContenedor As Nullable(Of Long)) As ObjectResult(Of CORE_DocumentosXHilo_Get_Result)
        Dim idContenedorParameter As ObjectParameter = If(idContenedor.HasValue, New ObjectParameter("IdContenedor", idContenedor), New ObjectParameter("IdContenedor", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_DocumentosXHilo_Get_Result)("CORE_DocumentosXHilo_Get", idContenedorParameter)
    End Function

    Public Overridable Function CORE_ObservacionesTareas_Get(core_WorkFlow_Id As Nullable(Of Long)) As ObjectResult(Of CORE_ObservacionesTareas_Get_Result)
        Dim core_WorkFlow_IdParameter As ObjectParameter = If(core_WorkFlow_Id.HasValue, New ObjectParameter("core_WorkFlow_Id", core_WorkFlow_Id), New ObjectParameter("core_WorkFlow_Id", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_ObservacionesTareas_Get_Result)("CORE_ObservacionesTareas_Get", core_WorkFlow_IdParameter)
    End Function

    Public Overridable Function CORE_TrabajosTareas_Get(coeId As Nullable(Of Long), gerenteProyectosId As Nullable(Of Long), core_UnidadId As Nullable(Of Long), unidadesId As String, nombreTrabajo As String, codEstadoActual As Nullable(Of Long), paginaActual As Nullable(Of Decimal), tamanoPagina As Nullable(Of Decimal), anoRegistro As Nullable(Of Decimal), mesRegistro As Nullable(Of Decimal)) As ObjectResult(Of CORE_TrabajosTareas_Get_Result)
        Dim coeIdParameter As ObjectParameter = If(coeId.HasValue, New ObjectParameter("CoeId", coeId), New ObjectParameter("CoeId", GetType(Long)))

        Dim gerenteProyectosIdParameter As ObjectParameter = If(gerenteProyectosId.HasValue, New ObjectParameter("GerenteProyectosId", gerenteProyectosId), New ObjectParameter("GerenteProyectosId", GetType(Long)))

        Dim core_UnidadIdParameter As ObjectParameter = If(core_UnidadId.HasValue, New ObjectParameter("Core_UnidadId", core_UnidadId), New ObjectParameter("Core_UnidadId", GetType(Long)))

        Dim unidadesIdParameter As ObjectParameter = If(unidadesId IsNot Nothing, New ObjectParameter("UnidadesId", unidadesId), New ObjectParameter("UnidadesId", GetType(String)))

        Dim nombreTrabajoParameter As ObjectParameter = If(nombreTrabajo IsNot Nothing, New ObjectParameter("NombreTrabajo", nombreTrabajo), New ObjectParameter("NombreTrabajo", GetType(String)))

        Dim codEstadoActualParameter As ObjectParameter = If(codEstadoActual.HasValue, New ObjectParameter("CodEstadoActual", codEstadoActual), New ObjectParameter("CodEstadoActual", GetType(Long)))

        Dim paginaActualParameter As ObjectParameter = If(paginaActual.HasValue, New ObjectParameter("PaginaActual", paginaActual), New ObjectParameter("PaginaActual", GetType(Decimal)))

        Dim tamanoPaginaParameter As ObjectParameter = If(tamanoPagina.HasValue, New ObjectParameter("TamanoPagina", tamanoPagina), New ObjectParameter("TamanoPagina", GetType(Decimal)))

        Dim anoRegistroParameter As ObjectParameter = If(anoRegistro.HasValue, New ObjectParameter("anoRegistro", anoRegistro), New ObjectParameter("anoRegistro", GetType(Decimal)))

        Dim mesRegistroParameter As ObjectParameter = If(mesRegistro.HasValue, New ObjectParameter("mesRegistro", mesRegistro), New ObjectParameter("mesRegistro", GetType(Decimal)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_TrabajosTareas_Get_Result)("CORE_TrabajosTareas_Get", coeIdParameter, gerenteProyectosIdParameter, core_UnidadIdParameter, unidadesIdParameter, nombreTrabajoParameter, codEstadoActualParameter, paginaActualParameter, tamanoPaginaParameter, anoRegistroParameter, mesRegistroParameter)
    End Function
    Public Overridable Function CORE_TrabajosTareas_Count_Get(coeId As Nullable(Of Long), gerenteProyectosId As Nullable(Of Long), core_UnidadId As Nullable(Of Long), unidadesId As String, nombreTrabajo As String, codEstadoActual As Nullable(Of Long), anoRegistro As Nullable(Of Decimal), mesRegistro As Nullable(Of Decimal)) As ObjectResult(Of Nullable(Of Integer))
        Dim coeIdParameter As ObjectParameter = If(coeId.HasValue, New ObjectParameter("CoeId", coeId), New ObjectParameter("CoeId", GetType(Long)))

        Dim gerenteProyectosIdParameter As ObjectParameter = If(gerenteProyectosId.HasValue, New ObjectParameter("GerenteProyectosId", gerenteProyectosId), New ObjectParameter("GerenteProyectosId", GetType(Long)))

        Dim core_UnidadIdParameter As ObjectParameter = If(core_UnidadId.HasValue, New ObjectParameter("Core_UnidadId", core_UnidadId), New ObjectParameter("Core_UnidadId", GetType(Long)))

        Dim unidadesIdParameter As ObjectParameter = If(unidadesId IsNot Nothing, New ObjectParameter("UnidadesId", unidadesId), New ObjectParameter("UnidadesId", GetType(String)))

        Dim nombreTrabajoParameter As ObjectParameter = If(nombreTrabajo IsNot Nothing, New ObjectParameter("NombreTrabajo", nombreTrabajo), New ObjectParameter("NombreTrabajo", GetType(String)))

        Dim codEstadoActualParameter As ObjectParameter = If(codEstadoActual.HasValue, New ObjectParameter("CodEstadoActual", codEstadoActual), New ObjectParameter("CodEstadoActual", GetType(Long)))

        Dim anoRegistroParameter As ObjectParameter = If(anoRegistro.HasValue, New ObjectParameter("anoRegistro", anoRegistro), New ObjectParameter("anoRegistro", GetType(Decimal)))

        Dim mesRegistroParameter As ObjectParameter = If(mesRegistro.HasValue, New ObjectParameter("mesRegistro", mesRegistro), New ObjectParameter("mesRegistro", GetType(Decimal)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("CORE_TrabajosTareas_Count_Get", coeIdParameter, gerenteProyectosIdParameter, core_UnidadIdParameter, unidadesIdParameter, nombreTrabajoParameter, codEstadoActualParameter, anoRegistroParameter, mesRegistroParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_GetXTrabajoXTarea(trabajoid As Nullable(Of Long), tareaid As Nullable(Of Long)) As ObjectResult(Of CORE_WorkFlow_GetXTrabajoXTarea_Result)
        Dim trabajoidParameter As ObjectParameter = If(trabajoid.HasValue, New ObjectParameter("trabajoid", trabajoid), New ObjectParameter("trabajoid", GetType(Long)))

        Dim tareaidParameter As ObjectParameter = If(tareaid.HasValue, New ObjectParameter("tareaid", tareaid), New ObjectParameter("tareaid", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_WorkFlow_GetXTrabajoXTarea_Result)("CORE_WorkFlow_GetXTrabajoXTarea", trabajoidParameter, tareaidParameter)
    End Function

    Public Overridable Function CORE_DestinatariosCorreosNotificacionFecha(tareaId As Nullable(Of Long), trabajoId As Nullable(Of Long)) As ObjectResult(Of CORE_DestinatariosCorreosNotificacionFecha_Result)
        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("TareaId", tareaId), New ObjectParameter("TareaId", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_DestinatariosCorreosNotificacionFecha_Result)("CORE_DestinatariosCorreosNotificacionFecha", tareaIdParameter, trabajoIdParameter)
    End Function

    Public Overridable Function CT_TareasPrevias(tipoHiloId As Nullable(Of Long), wFId As Nullable(Of Long), trabajoId As Nullable(Of Long)) As ObjectResult(Of CT_TareasList_Result)
        Dim tipoHiloIdParameter As ObjectParameter = If(tipoHiloId.HasValue, New ObjectParameter("TipoHiloId", tipoHiloId), New ObjectParameter("TipoHiloId", GetType(Long)))

        Dim wFIdParameter As ObjectParameter = If(wFId.HasValue, New ObjectParameter("WFId", wFId), New ObjectParameter("WFId", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("trabajoId", trabajoId), New ObjectParameter("trabajoId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CT_TareasList_Result)("CT_TareasPrevias", tipoHiloIdParameter, wFIdParameter, trabajoIdParameter)
    End Function

    Public Overridable Function Core_Log_Entrada_Add(usuarioId As Nullable(Of Long), fecha As Nullable(Of Date), ip As String, nomEquipo As String) As Integer
        Dim usuarioIdParameter As ObjectParameter = If(usuarioId.HasValue, New ObjectParameter("UsuarioId", usuarioId), New ObjectParameter("UsuarioId", GetType(Long)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim ipParameter As ObjectParameter = If(ip IsNot Nothing, New ObjectParameter("Ip", ip), New ObjectParameter("Ip", GetType(String)))

        Dim nomEquipoParameter As ObjectParameter = If(nomEquipo IsNot Nothing, New ObjectParameter("NomEquipo", nomEquipo), New ObjectParameter("NomEquipo", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Core_Log_Entrada_Add", usuarioIdParameter, fechaParameter, ipParameter, nomEquipoParameter)
    End Function

    Public Overridable Function CT_TareasTrabajosList(usuarioId As Nullable(Of Long), estado As Nullable(Of Integer)) As ObjectResult(Of CT_TareasTrabajosList_Result)
        Dim usuarioIdParameter As ObjectParameter = If(usuarioId.HasValue, New ObjectParameter("UsuarioId", usuarioId), New ObjectParameter("UsuarioId", GetType(Long)))

        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("Estado", estado), New ObjectParameter("Estado", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CT_TareasTrabajosList_Result)("CT_TareasTrabajosList", usuarioIdParameter, estadoParameter)
    End Function

    Public Overridable Function CT_TareasListPendientesAsignacion(tareaWFId As Nullable(Of Long), trabajoId As Nullable(Of Long), rolEstima As Nullable(Of Long), unidadEjecuta As Nullable(Of Long), estadoNo As Nullable(Of Integer), usuarioId As Nullable(Of Long), estado As Nullable(Of Integer)) As ObjectResult(Of CT_TareasList_Result)
        Dim tareaWFIdParameter As ObjectParameter = If(tareaWFId.HasValue, New ObjectParameter("TareaWFId", tareaWFId), New ObjectParameter("TareaWFId", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim rolEstimaParameter As ObjectParameter = If(rolEstima.HasValue, New ObjectParameter("RolEstima", rolEstima), New ObjectParameter("RolEstima", GetType(Long)))

        Dim unidadEjecutaParameter As ObjectParameter = If(unidadEjecuta.HasValue, New ObjectParameter("UnidadEjecuta", unidadEjecuta), New ObjectParameter("UnidadEjecuta", GetType(Long)))

        Dim estadoNoParameter As ObjectParameter = If(estadoNo.HasValue, New ObjectParameter("EstadoNo", estadoNo), New ObjectParameter("EstadoNo", GetType(Integer)))

        Dim usuarioIdParameter As ObjectParameter = If(usuarioId.HasValue, New ObjectParameter("UsuarioId", usuarioId), New ObjectParameter("UsuarioId", GetType(Long)))

        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("Estado", estado), New ObjectParameter("Estado", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CT_TareasList_Result)("CT_TareasListPendientesAsignacion", tareaWFIdParameter, trabajoIdParameter, rolEstimaParameter, unidadEjecutaParameter, estadoNoParameter, usuarioIdParameter, estadoParameter)
    End Function

    Public Overridable Function CT_UnidadesAsignacionXUsuario(uSUARIO As Nullable(Of Long)) As ObjectResult(Of CT_UnidadesAsignacionXUsuario_Result)
        Dim uSUARIOParameter As ObjectParameter = If(uSUARIO.HasValue, New ObjectParameter("USUARIO", uSUARIO), New ObjectParameter("USUARIO", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CT_UnidadesAsignacionXUsuario_Result)("CT_UnidadesAsignacionXUsuario", uSUARIOParameter)
    End Function

    Public Overridable Function CORE_HilosGetxContenedor(cONTENEDOR As Nullable(Of Long)) As ObjectResult(Of CORE_HilosGetxContenedor_Result)
        Dim cONTENEDORParameter As ObjectParameter = If(cONTENEDOR.HasValue, New ObjectParameter("CONTENEDOR", cONTENEDOR), New ObjectParameter("CONTENEDOR", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_HilosGetxContenedor_Result)("CORE_HilosGetxContenedor", cONTENEDORParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_GetxHiloid(hiloid As Nullable(Of Integer)) As ObjectResult(Of CORE_WorkFlow_GetxHiloid_Result)
        Dim hiloidParameter As ObjectParameter = If(hiloid.HasValue, New ObjectParameter("Hiloid", hiloid), New ObjectParameter("Hiloid", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_WorkFlow_GetxHiloid_Result)("CORE_WorkFlow_GetxHiloid", hiloidParameter)
    End Function

    Public Overridable Function CORE_WorkFlow_AddDuplicados(tareaId As Nullable(Of Long), hilo As Nullable(Of Long), fIniP As Nullable(Of Date), fFinP As Nullable(Of Date), fIniR As Nullable(Of Date), fFinR As Nullable(Of Date), usuarioEstima As Nullable(Of Long), usuarioAsignado As Nullable(Of Long), estado As Nullable(Of Byte), fechaUltimoEstado As Nullable(Of Date), observacionesPlaneacion As String, observacionesEjecucion As String, descripcion As String) As Integer
        Dim tareaIdParameter As ObjectParameter = If(tareaId.HasValue, New ObjectParameter("TareaId", tareaId), New ObjectParameter("TareaId", GetType(Long)))

        Dim hiloParameter As ObjectParameter = If(hilo.HasValue, New ObjectParameter("Hilo", hilo), New ObjectParameter("Hilo", GetType(Long)))

        Dim fIniPParameter As ObjectParameter = If(fIniP.HasValue, New ObjectParameter("FIniP", fIniP), New ObjectParameter("FIniP", GetType(Date)))

        Dim fFinPParameter As ObjectParameter = If(fFinP.HasValue, New ObjectParameter("FFinP", fFinP), New ObjectParameter("FFinP", GetType(Date)))

        Dim fIniRParameter As ObjectParameter = If(fIniR.HasValue, New ObjectParameter("FIniR", fIniR), New ObjectParameter("FIniR", GetType(Date)))

        Dim fFinRParameter As ObjectParameter = If(fFinR.HasValue, New ObjectParameter("FFinR", fFinR), New ObjectParameter("FFinR", GetType(Date)))

        Dim usuarioEstimaParameter As ObjectParameter = If(usuarioEstima.HasValue, New ObjectParameter("UsuarioEstima", usuarioEstima), New ObjectParameter("UsuarioEstima", GetType(Long)))

        Dim usuarioAsignadoParameter As ObjectParameter = If(usuarioAsignado.HasValue, New ObjectParameter("UsuarioAsignado", usuarioAsignado), New ObjectParameter("UsuarioAsignado", GetType(Long)))

        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("Estado", estado), New ObjectParameter("Estado", GetType(Byte)))

        Dim fechaUltimoEstadoParameter As ObjectParameter = If(fechaUltimoEstado.HasValue, New ObjectParameter("FechaUltimoEstado", fechaUltimoEstado), New ObjectParameter("FechaUltimoEstado", GetType(Date)))

        Dim observacionesPlaneacionParameter As ObjectParameter = If(observacionesPlaneacion IsNot Nothing, New ObjectParameter("ObservacionesPlaneacion", observacionesPlaneacion), New ObjectParameter("ObservacionesPlaneacion", GetType(String)))

        Dim observacionesEjecucionParameter As ObjectParameter = If(observacionesEjecucion IsNot Nothing, New ObjectParameter("ObservacionesEjecucion", observacionesEjecucion), New ObjectParameter("ObservacionesEjecucion", GetType(String)))

        Dim descripcionParameter As ObjectParameter = If(descripcion IsNot Nothing, New ObjectParameter("Descripcion", descripcion), New ObjectParameter("Descripcion", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("CORE_WorkFlow_AddDuplicados", tareaIdParameter, hiloParameter, fIniPParameter, fFinPParameter, fIniRParameter, fFinRParameter, usuarioEstimaParameter, usuarioAsignadoParameter, estadoParameter, fechaUltimoEstadoParameter, observacionesPlaneacionParameter, observacionesEjecucionParameter, descripcionParameter)
    End Function

    Public Overridable Function CT_TareasList(tareaWFId As Nullable(Of Long), trabajoId As Nullable(Of Long), rolEstima As Nullable(Of Long), unidadEjecuta As Nullable(Of Long), estadoNo As Nullable(Of Integer), usuarioId As Nullable(Of Long), estado As Nullable(Of Integer), fIniP As Nullable(Of Date), fFinP As Nullable(Of Date), fIniR As Nullable(Of Date), fFinR As Nullable(Of Date)) As ObjectResult(Of CT_TareasList_Result)
        Dim tareaWFIdParameter As ObjectParameter = If(tareaWFId.HasValue, New ObjectParameter("TareaWFId", tareaWFId), New ObjectParameter("TareaWFId", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim rolEstimaParameter As ObjectParameter = If(rolEstima.HasValue, New ObjectParameter("RolEstima", rolEstima), New ObjectParameter("RolEstima", GetType(Long)))

        Dim unidadEjecutaParameter As ObjectParameter = If(unidadEjecuta.HasValue, New ObjectParameter("UnidadEjecuta", unidadEjecuta), New ObjectParameter("UnidadEjecuta", GetType(Long)))

        Dim estadoNoParameter As ObjectParameter = If(estadoNo.HasValue, New ObjectParameter("EstadoNo", estadoNo), New ObjectParameter("EstadoNo", GetType(Integer)))

        Dim usuarioIdParameter As ObjectParameter = If(usuarioId.HasValue, New ObjectParameter("UsuarioId", usuarioId), New ObjectParameter("UsuarioId", GetType(Long)))

        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("Estado", estado), New ObjectParameter("Estado", GetType(Integer)))

        Dim fIniPParameter As ObjectParameter = If(fIniP.HasValue, New ObjectParameter("FIniP", fIniP), New ObjectParameter("FIniP", GetType(Date)))

        Dim fFinPParameter As ObjectParameter = If(fFinP.HasValue, New ObjectParameter("FFinP", fFinP), New ObjectParameter("FFinP", GetType(Date)))

        Dim fIniRParameter As ObjectParameter = If(fIniR.HasValue, New ObjectParameter("FIniR", fIniR), New ObjectParameter("FIniR", GetType(Date)))

        Dim fFinRParameter As ObjectParameter = If(fFinR.HasValue, New ObjectParameter("FFinR", fFinR), New ObjectParameter("FFinR", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CT_TareasList_Result)("CT_TareasList", tareaWFIdParameter, trabajoIdParameter, rolEstimaParameter, unidadEjecutaParameter, estadoNoParameter, usuarioIdParameter, estadoParameter, fIniPParameter, fFinPParameter, fIniRParameter, fFinRParameter)
    End Function

    Public Overridable Function Core_UnidadesAll() As ObjectResult(Of Core_UnidadesAll_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Core_UnidadesAll_Result)("Core_UnidadesAll")
    End Function

    Public Overridable Function CORE_obtenerusuariosasignados_get(idtrabajo As Nullable(Of Long), rolid As Nullable(Of Long)) As ObjectResult(Of CORE_obtenerusuariosasignados_get_Result)
        Dim idtrabajoParameter As ObjectParameter = If(idtrabajo.HasValue, New ObjectParameter("idtrabajo", idtrabajo), New ObjectParameter("idtrabajo", GetType(Long)))

        Dim rolidParameter As ObjectParameter = If(rolid.HasValue, New ObjectParameter("rolid", rolid), New ObjectParameter("rolid", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_obtenerusuariosasignados_get_Result)("CORE_obtenerusuariosasignados_get", idtrabajoParameter, rolidParameter)
    End Function

    Public Overridable Function f_Constantes_Get(id As Nullable(Of Integer)) As ObjectResult(Of f_Constantes_Get_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of f_Constantes_Get_Result)("f_Constantes_Get", idParameter)
    End Function

    Public Overridable Function CORE_TareasXUnidadEjecuta(unidadEjecuta As Nullable(Of Long)) As ObjectResult(Of CORE_TareasXUnidadEjecuta_Result)
        Dim unidadEjecutaParameter As ObjectParameter = If(unidadEjecuta.HasValue, New ObjectParameter("unidadEjecuta", unidadEjecuta), New ObjectParameter("unidadEjecuta", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_TareasXUnidadEjecuta_Result)("CORE_TareasXUnidadEjecuta", unidadEjecutaParameter)
    End Function

    Public Overridable Function CORE_UsuariosAsignadosXProceso(idProceso As Nullable(Of Byte)) As ObjectResult(Of CORE_UsuariosAsignadosXProceso_Result)
        Dim idProcesoParameter As ObjectParameter = If(idProceso.HasValue, New ObjectParameter("idProceso", idProceso), New ObjectParameter("idProceso", GetType(Byte)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CORE_UsuariosAsignadosXProceso_Result)("CORE_UsuariosAsignadosXProceso", idProcesoParameter)
    End Function

End Class
