'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CU_Presupuestos
    Public Property Id As Long
    Public Property PropuestaId As Nullable(Of Long)
    Public Property Valor As Nullable(Of Double)
    Public Property Muestra As Nullable(Of Long)
    Public Property ProductoId As Nullable(Of Integer)
    Public Property GrossMargin As Nullable(Of Double)
    Public Property UsadoPropuesta As Nullable(Of Boolean)
    Public Property Alternativa As Nullable(Of Long)
    Public Property JobBook As String
    Public Property EstadoId As Nullable(Of Byte)
    Public Property Nombre As String
    Public Property Aprobado As Nullable(Of Boolean)
    Public Property ParaRevisar As Nullable(Of Boolean)
    Public Property Visible As Nullable(Of Boolean)
    Public Property Nacional As Nullable(Of Boolean)

    Public Overridable Property CU_Estudios_Presupuestos As ICollection(Of CU_Estudios_Presupuestos) = New HashSet(Of CU_Estudios_Presupuestos)
    Public Overridable Property CU_Propuestas As CU_Propuestas

End Class
