'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ES_BriefDisenoMuestral
    Public Property id As Long
    Public Property Propuestaid As Nullable(Of Long)
    Public Property Fecha As Nullable(Of Date)
    Public Property Objetivo As String
    Public Property Poblacion As String
    Public Property Capacidad As String
    Public Property Metodologia As String
    Public Property NivelesDesagregacion As String
    Public Property PosiblesMarcos As String
    Public Property Variable As String
    Public Property Observaciones As String
    Public Property NoVersion As Nullable(Of Integer)

    Public Overridable Property ES_DisenoMuestral As ICollection(Of ES_DisenoMuestral) = New HashSet(Of ES_DisenoMuestral)

End Class
