'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class ES_Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ES_Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ES_BriefDisenoMuestral() As DbSet(Of ES_BriefDisenoMuestral)
    Public Overridable Property ES_DisenoMuestral() As DbSet(Of ES_DisenoMuestral)
    Public Overridable Property ES_MetodologiaCampo() As DbSet(Of ES_MetodologiaCampo)
    Public Overridable Property ES_AprobacionMetodologia() As DbSet(Of ES_AprobacionMetodologia)

    Public Overridable Function ES_BriefDisenoMuestral_Add(propuestaid As Nullable(Of Long), fecha As Nullable(Of Date), objetivo As String, poblacion As String, capacidad As String, metodologia As String, nivelesDesagregacion As String, posiblesMarcos As String, variable As String, observaciones As String, noVersion As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Decimal))
        Dim propuestaidParameter As ObjectParameter = If(propuestaid.HasValue, New ObjectParameter("Propuestaid", propuestaid), New ObjectParameter("Propuestaid", GetType(Long)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim objetivoParameter As ObjectParameter = If(objetivo IsNot Nothing, New ObjectParameter("Objetivo", objetivo), New ObjectParameter("Objetivo", GetType(String)))

        Dim poblacionParameter As ObjectParameter = If(poblacion IsNot Nothing, New ObjectParameter("Poblacion", poblacion), New ObjectParameter("Poblacion", GetType(String)))

        Dim capacidadParameter As ObjectParameter = If(capacidad IsNot Nothing, New ObjectParameter("Capacidad", capacidad), New ObjectParameter("Capacidad", GetType(String)))

        Dim metodologiaParameter As ObjectParameter = If(metodologia IsNot Nothing, New ObjectParameter("Metodologia", metodologia), New ObjectParameter("Metodologia", GetType(String)))

        Dim nivelesDesagregacionParameter As ObjectParameter = If(nivelesDesagregacion IsNot Nothing, New ObjectParameter("NivelesDesagregacion", nivelesDesagregacion), New ObjectParameter("NivelesDesagregacion", GetType(String)))

        Dim posiblesMarcosParameter As ObjectParameter = If(posiblesMarcos IsNot Nothing, New ObjectParameter("PosiblesMarcos", posiblesMarcos), New ObjectParameter("PosiblesMarcos", GetType(String)))

        Dim variableParameter As ObjectParameter = If(variable IsNot Nothing, New ObjectParameter("Variable", variable), New ObjectParameter("Variable", GetType(String)))

        Dim observacionesParameter As ObjectParameter = If(observaciones IsNot Nothing, New ObjectParameter("Observaciones", observaciones), New ObjectParameter("Observaciones", GetType(String)))

        Dim noVersionParameter As ObjectParameter = If(noVersion.HasValue, New ObjectParameter("NoVersion", noVersion), New ObjectParameter("NoVersion", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Decimal))("ES_BriefDisenoMuestral_Add", propuestaidParameter, fechaParameter, objetivoParameter, poblacionParameter, capacidadParameter, metodologiaParameter, nivelesDesagregacionParameter, posiblesMarcosParameter, variableParameter, observacionesParameter, noVersionParameter)
    End Function

    Public Overridable Function ES_BriefDisenoMuestral_Edit(id As Nullable(Of Long), propuestaid As Nullable(Of Long), fecha As Nullable(Of Date), objetivo As String, poblacion As String, capacidad As String, metodologia As String, nivelesDesagregacion As String, posiblesMarcos As String, variable As String, observaciones As String, noVersion As Nullable(Of Integer)) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Dim propuestaidParameter As ObjectParameter = If(propuestaid.HasValue, New ObjectParameter("Propuestaid", propuestaid), New ObjectParameter("Propuestaid", GetType(Long)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim objetivoParameter As ObjectParameter = If(objetivo IsNot Nothing, New ObjectParameter("Objetivo", objetivo), New ObjectParameter("Objetivo", GetType(String)))

        Dim poblacionParameter As ObjectParameter = If(poblacion IsNot Nothing, New ObjectParameter("Poblacion", poblacion), New ObjectParameter("Poblacion", GetType(String)))

        Dim capacidadParameter As ObjectParameter = If(capacidad IsNot Nothing, New ObjectParameter("Capacidad", capacidad), New ObjectParameter("Capacidad", GetType(String)))

        Dim metodologiaParameter As ObjectParameter = If(metodologia IsNot Nothing, New ObjectParameter("Metodologia", metodologia), New ObjectParameter("Metodologia", GetType(String)))

        Dim nivelesDesagregacionParameter As ObjectParameter = If(nivelesDesagregacion IsNot Nothing, New ObjectParameter("NivelesDesagregacion", nivelesDesagregacion), New ObjectParameter("NivelesDesagregacion", GetType(String)))

        Dim posiblesMarcosParameter As ObjectParameter = If(posiblesMarcos IsNot Nothing, New ObjectParameter("PosiblesMarcos", posiblesMarcos), New ObjectParameter("PosiblesMarcos", GetType(String)))

        Dim variableParameter As ObjectParameter = If(variable IsNot Nothing, New ObjectParameter("Variable", variable), New ObjectParameter("Variable", GetType(String)))

        Dim observacionesParameter As ObjectParameter = If(observaciones IsNot Nothing, New ObjectParameter("Observaciones", observaciones), New ObjectParameter("Observaciones", GetType(String)))

        Dim noVersionParameter As ObjectParameter = If(noVersion.HasValue, New ObjectParameter("NoVersion", noVersion), New ObjectParameter("NoVersion", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ES_BriefDisenoMuestral_Edit", idParameter, propuestaidParameter, fechaParameter, objetivoParameter, poblacionParameter, capacidadParameter, metodologiaParameter, nivelesDesagregacionParameter, posiblesMarcosParameter, variableParameter, observacionesParameter, noVersionParameter)
    End Function

    Public Overridable Function ES_DisenoMuestral_Add(briefId As Nullable(Of Long), fecha As Nullable(Of Date), muestroProbabilistico As Nullable(Of Boolean), objetivo As Nullable(Of Boolean), poblacion As Nullable(Of Boolean), mercado As Nullable(Of Boolean), marco As Nullable(Of Boolean), tecnica As Nullable(Of Boolean), diseno As Nullable(Of Boolean), tamano As Nullable(Of Boolean), fiabilidad As Nullable(Of Boolean), desagregacion As Nullable(Of Boolean), fuente As Nullable(Of Boolean), ponderacion As Nullable(Of Boolean), objetivoT As String, poblacionT As String, mercadoT As String, marcoT As String, tecnicaT As String, disenoT As String, tamanoT As String, fiabilidadT As String, desagregacionT As String, fuenteT As String, ponderacionT As String, variable As Nullable(Of Boolean), variableT As String, observaciones As String, observacionesT As String, noVersion As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Decimal))
        Dim briefIdParameter As ObjectParameter = If(briefId.HasValue, New ObjectParameter("BriefId", briefId), New ObjectParameter("BriefId", GetType(Long)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim muestroProbabilisticoParameter As ObjectParameter = If(muestroProbabilistico.HasValue, New ObjectParameter("MuestroProbabilistico", muestroProbabilistico), New ObjectParameter("MuestroProbabilistico", GetType(Boolean)))

        Dim objetivoParameter As ObjectParameter = If(objetivo.HasValue, New ObjectParameter("Objetivo", objetivo), New ObjectParameter("Objetivo", GetType(Boolean)))

        Dim poblacionParameter As ObjectParameter = If(poblacion.HasValue, New ObjectParameter("Poblacion", poblacion), New ObjectParameter("Poblacion", GetType(Boolean)))

        Dim mercadoParameter As ObjectParameter = If(mercado.HasValue, New ObjectParameter("Mercado", mercado), New ObjectParameter("Mercado", GetType(Boolean)))

        Dim marcoParameter As ObjectParameter = If(marco.HasValue, New ObjectParameter("Marco", marco), New ObjectParameter("Marco", GetType(Boolean)))

        Dim tecnicaParameter As ObjectParameter = If(tecnica.HasValue, New ObjectParameter("Tecnica", tecnica), New ObjectParameter("Tecnica", GetType(Boolean)))

        Dim disenoParameter As ObjectParameter = If(diseno.HasValue, New ObjectParameter("Diseno", diseno), New ObjectParameter("Diseno", GetType(Boolean)))

        Dim tamanoParameter As ObjectParameter = If(tamano.HasValue, New ObjectParameter("Tamano", tamano), New ObjectParameter("Tamano", GetType(Boolean)))

        Dim fiabilidadParameter As ObjectParameter = If(fiabilidad.HasValue, New ObjectParameter("Fiabilidad", fiabilidad), New ObjectParameter("Fiabilidad", GetType(Boolean)))

        Dim desagregacionParameter As ObjectParameter = If(desagregacion.HasValue, New ObjectParameter("Desagregacion", desagregacion), New ObjectParameter("Desagregacion", GetType(Boolean)))

        Dim fuenteParameter As ObjectParameter = If(fuente.HasValue, New ObjectParameter("Fuente", fuente), New ObjectParameter("Fuente", GetType(Boolean)))

        Dim ponderacionParameter As ObjectParameter = If(ponderacion.HasValue, New ObjectParameter("Ponderacion", ponderacion), New ObjectParameter("Ponderacion", GetType(Boolean)))

        Dim objetivoTParameter As ObjectParameter = If(objetivoT IsNot Nothing, New ObjectParameter("ObjetivoT", objetivoT), New ObjectParameter("ObjetivoT", GetType(String)))

        Dim poblacionTParameter As ObjectParameter = If(poblacionT IsNot Nothing, New ObjectParameter("PoblacionT", poblacionT), New ObjectParameter("PoblacionT", GetType(String)))

        Dim mercadoTParameter As ObjectParameter = If(mercadoT IsNot Nothing, New ObjectParameter("MercadoT", mercadoT), New ObjectParameter("MercadoT", GetType(String)))

        Dim marcoTParameter As ObjectParameter = If(marcoT IsNot Nothing, New ObjectParameter("MarcoT", marcoT), New ObjectParameter("MarcoT", GetType(String)))

        Dim tecnicaTParameter As ObjectParameter = If(tecnicaT IsNot Nothing, New ObjectParameter("TecnicaT", tecnicaT), New ObjectParameter("TecnicaT", GetType(String)))

        Dim disenoTParameter As ObjectParameter = If(disenoT IsNot Nothing, New ObjectParameter("DisenoT", disenoT), New ObjectParameter("DisenoT", GetType(String)))

        Dim tamanoTParameter As ObjectParameter = If(tamanoT IsNot Nothing, New ObjectParameter("TamanoT", tamanoT), New ObjectParameter("TamanoT", GetType(String)))

        Dim fiabilidadTParameter As ObjectParameter = If(fiabilidadT IsNot Nothing, New ObjectParameter("FiabilidadT", fiabilidadT), New ObjectParameter("FiabilidadT", GetType(String)))

        Dim desagregacionTParameter As ObjectParameter = If(desagregacionT IsNot Nothing, New ObjectParameter("DesagregacionT", desagregacionT), New ObjectParameter("DesagregacionT", GetType(String)))

        Dim fuenteTParameter As ObjectParameter = If(fuenteT IsNot Nothing, New ObjectParameter("FuenteT", fuenteT), New ObjectParameter("FuenteT", GetType(String)))

        Dim ponderacionTParameter As ObjectParameter = If(ponderacionT IsNot Nothing, New ObjectParameter("PonderacionT", ponderacionT), New ObjectParameter("PonderacionT", GetType(String)))

        Dim variableParameter As ObjectParameter = If(variable.HasValue, New ObjectParameter("Variable", variable), New ObjectParameter("Variable", GetType(Boolean)))

        Dim variableTParameter As ObjectParameter = If(variableT IsNot Nothing, New ObjectParameter("VariableT", variableT), New ObjectParameter("VariableT", GetType(String)))

        Dim observacionesParameter As ObjectParameter = If(observaciones IsNot Nothing, New ObjectParameter("Observaciones", observaciones), New ObjectParameter("Observaciones", GetType(String)))

        Dim observacionesTParameter As ObjectParameter = If(observacionesT IsNot Nothing, New ObjectParameter("ObservacionesT", observacionesT), New ObjectParameter("ObservacionesT", GetType(String)))

        Dim noVersionParameter As ObjectParameter = If(noVersion.HasValue, New ObjectParameter("NoVersion", noVersion), New ObjectParameter("NoVersion", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Decimal))("ES_DisenoMuestral_Add", briefIdParameter, fechaParameter, muestroProbabilisticoParameter, objetivoParameter, poblacionParameter, mercadoParameter, marcoParameter, tecnicaParameter, disenoParameter, tamanoParameter, fiabilidadParameter, desagregacionParameter, fuenteParameter, ponderacionParameter, objetivoTParameter, poblacionTParameter, mercadoTParameter, marcoTParameter, tecnicaTParameter, disenoTParameter, tamanoTParameter, fiabilidadTParameter, desagregacionTParameter, fuenteTParameter, ponderacionTParameter, variableParameter, variableTParameter, observacionesParameter, observacionesTParameter, noVersionParameter)
    End Function

    Public Overridable Function ES_DisenoMuestral_Edit(id As Nullable(Of Long), briefId As Nullable(Of Long), fecha As Nullable(Of Date), muestroProbabilistico As Nullable(Of Boolean), objetivo As Nullable(Of Boolean), poblacion As Nullable(Of Boolean), mercado As Nullable(Of Boolean), marco As Nullable(Of Boolean), tecnica As Nullable(Of Boolean), diseno As Nullable(Of Boolean), tamano As Nullable(Of Boolean), fiabilidad As Nullable(Of Boolean), desagregacion As Nullable(Of Boolean), fuente As Nullable(Of Boolean), ponderacion As Nullable(Of Boolean), objetivoT As String, poblacionT As String, mercadoT As String, marcoT As String, tecnicaT As String, disenoT As String, tamanoT As String, fiabilidadT As String, desagregacionT As String, fuenteT As String, ponderacionT As String, variable As Nullable(Of Boolean), variableT As String, observaciones As String, observacionesT As String, noVersion As Nullable(Of Integer)) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Dim briefIdParameter As ObjectParameter = If(briefId.HasValue, New ObjectParameter("BriefId", briefId), New ObjectParameter("BriefId", GetType(Long)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim muestroProbabilisticoParameter As ObjectParameter = If(muestroProbabilistico.HasValue, New ObjectParameter("MuestroProbabilistico", muestroProbabilistico), New ObjectParameter("MuestroProbabilistico", GetType(Boolean)))

        Dim objetivoParameter As ObjectParameter = If(objetivo.HasValue, New ObjectParameter("Objetivo", objetivo), New ObjectParameter("Objetivo", GetType(Boolean)))

        Dim poblacionParameter As ObjectParameter = If(poblacion.HasValue, New ObjectParameter("Poblacion", poblacion), New ObjectParameter("Poblacion", GetType(Boolean)))

        Dim mercadoParameter As ObjectParameter = If(mercado.HasValue, New ObjectParameter("Mercado", mercado), New ObjectParameter("Mercado", GetType(Boolean)))

        Dim marcoParameter As ObjectParameter = If(marco.HasValue, New ObjectParameter("Marco", marco), New ObjectParameter("Marco", GetType(Boolean)))

        Dim tecnicaParameter As ObjectParameter = If(tecnica.HasValue, New ObjectParameter("Tecnica", tecnica), New ObjectParameter("Tecnica", GetType(Boolean)))

        Dim disenoParameter As ObjectParameter = If(diseno.HasValue, New ObjectParameter("Diseno", diseno), New ObjectParameter("Diseno", GetType(Boolean)))

        Dim tamanoParameter As ObjectParameter = If(tamano.HasValue, New ObjectParameter("Tamano", tamano), New ObjectParameter("Tamano", GetType(Boolean)))

        Dim fiabilidadParameter As ObjectParameter = If(fiabilidad.HasValue, New ObjectParameter("Fiabilidad", fiabilidad), New ObjectParameter("Fiabilidad", GetType(Boolean)))

        Dim desagregacionParameter As ObjectParameter = If(desagregacion.HasValue, New ObjectParameter("Desagregacion", desagregacion), New ObjectParameter("Desagregacion", GetType(Boolean)))

        Dim fuenteParameter As ObjectParameter = If(fuente.HasValue, New ObjectParameter("Fuente", fuente), New ObjectParameter("Fuente", GetType(Boolean)))

        Dim ponderacionParameter As ObjectParameter = If(ponderacion.HasValue, New ObjectParameter("Ponderacion", ponderacion), New ObjectParameter("Ponderacion", GetType(Boolean)))

        Dim objetivoTParameter As ObjectParameter = If(objetivoT IsNot Nothing, New ObjectParameter("ObjetivoT", objetivoT), New ObjectParameter("ObjetivoT", GetType(String)))

        Dim poblacionTParameter As ObjectParameter = If(poblacionT IsNot Nothing, New ObjectParameter("PoblacionT", poblacionT), New ObjectParameter("PoblacionT", GetType(String)))

        Dim mercadoTParameter As ObjectParameter = If(mercadoT IsNot Nothing, New ObjectParameter("MercadoT", mercadoT), New ObjectParameter("MercadoT", GetType(String)))

        Dim marcoTParameter As ObjectParameter = If(marcoT IsNot Nothing, New ObjectParameter("MarcoT", marcoT), New ObjectParameter("MarcoT", GetType(String)))

        Dim tecnicaTParameter As ObjectParameter = If(tecnicaT IsNot Nothing, New ObjectParameter("TecnicaT", tecnicaT), New ObjectParameter("TecnicaT", GetType(String)))

        Dim disenoTParameter As ObjectParameter = If(disenoT IsNot Nothing, New ObjectParameter("DisenoT", disenoT), New ObjectParameter("DisenoT", GetType(String)))

        Dim tamanoTParameter As ObjectParameter = If(tamanoT IsNot Nothing, New ObjectParameter("TamanoT", tamanoT), New ObjectParameter("TamanoT", GetType(String)))

        Dim fiabilidadTParameter As ObjectParameter = If(fiabilidadT IsNot Nothing, New ObjectParameter("FiabilidadT", fiabilidadT), New ObjectParameter("FiabilidadT", GetType(String)))

        Dim desagregacionTParameter As ObjectParameter = If(desagregacionT IsNot Nothing, New ObjectParameter("DesagregacionT", desagregacionT), New ObjectParameter("DesagregacionT", GetType(String)))

        Dim fuenteTParameter As ObjectParameter = If(fuenteT IsNot Nothing, New ObjectParameter("FuenteT", fuenteT), New ObjectParameter("FuenteT", GetType(String)))

        Dim ponderacionTParameter As ObjectParameter = If(ponderacionT IsNot Nothing, New ObjectParameter("PonderacionT", ponderacionT), New ObjectParameter("PonderacionT", GetType(String)))

        Dim variableParameter As ObjectParameter = If(variable.HasValue, New ObjectParameter("Variable", variable), New ObjectParameter("Variable", GetType(Boolean)))

        Dim variableTParameter As ObjectParameter = If(variableT IsNot Nothing, New ObjectParameter("VariableT", variableT), New ObjectParameter("VariableT", GetType(String)))

        Dim observacionesParameter As ObjectParameter = If(observaciones IsNot Nothing, New ObjectParameter("Observaciones", observaciones), New ObjectParameter("Observaciones", GetType(String)))

        Dim observacionesTParameter As ObjectParameter = If(observacionesT IsNot Nothing, New ObjectParameter("ObservacionesT", observacionesT), New ObjectParameter("ObservacionesT", GetType(String)))

        Dim noVersionParameter As ObjectParameter = If(noVersion.HasValue, New ObjectParameter("NoVersion", noVersion), New ObjectParameter("NoVersion", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ES_DisenoMuestral_Edit", idParameter, briefIdParameter, fechaParameter, muestroProbabilisticoParameter, objetivoParameter, poblacionParameter, mercadoParameter, marcoParameter, tecnicaParameter, disenoParameter, tamanoParameter, fiabilidadParameter, desagregacionParameter, fuenteParameter, ponderacionParameter, objetivoTParameter, poblacionTParameter, mercadoTParameter, marcoTParameter, tecnicaTParameter, disenoTParameter, tamanoTParameter, fiabilidadTParameter, desagregacionTParameter, fuenteTParameter, ponderacionTParameter, variableParameter, variableTParameter, observacionesParameter, observacionesTParameter, noVersionParameter)
    End Function

    Public Overridable Function ES_MetodologiaCampo_Add(trabajoId As Nullable(Of Long), nombreEstudio As String, fecha As Nullable(Of Date), objetivo As Nullable(Of Boolean), mercado As Nullable(Of Boolean), marco As Nullable(Of Boolean), tecnica As Nullable(Of Boolean), diseno As Nullable(Of Boolean), instrucciones As Nullable(Of Boolean), distribucion As Nullable(Of Boolean), nivelConfianza As Nullable(Of Boolean), margenError As Nullable(Of Boolean), desagregacion As Nullable(Of Boolean), fuente As Nullable(Of Boolean), variables As Nullable(Of Boolean), tasa As Nullable(Of Boolean), procedimiento As Nullable(Of Boolean), objetivoT As String, mercadoT As String, marcoT As String, tecnicaT As String, disenoT As String, instruccionesT As String, distribucionT As String, nivelConfianzaT As String, margenErrorT As String, desagregacionT As String, fuenteT As String, variablesT As String, tasaT As String, procedimientoT As String, version As Nullable(Of Byte), usuario As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Decimal))
        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim nombreEstudioParameter As ObjectParameter = If(nombreEstudio IsNot Nothing, New ObjectParameter("NombreEstudio", nombreEstudio), New ObjectParameter("NombreEstudio", GetType(String)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim objetivoParameter As ObjectParameter = If(objetivo.HasValue, New ObjectParameter("Objetivo", objetivo), New ObjectParameter("Objetivo", GetType(Boolean)))

        Dim mercadoParameter As ObjectParameter = If(mercado.HasValue, New ObjectParameter("Mercado", mercado), New ObjectParameter("Mercado", GetType(Boolean)))

        Dim marcoParameter As ObjectParameter = If(marco.HasValue, New ObjectParameter("Marco", marco), New ObjectParameter("Marco", GetType(Boolean)))

        Dim tecnicaParameter As ObjectParameter = If(tecnica.HasValue, New ObjectParameter("Tecnica", tecnica), New ObjectParameter("Tecnica", GetType(Boolean)))

        Dim disenoParameter As ObjectParameter = If(diseno.HasValue, New ObjectParameter("Diseno", diseno), New ObjectParameter("Diseno", GetType(Boolean)))

        Dim instruccionesParameter As ObjectParameter = If(instrucciones.HasValue, New ObjectParameter("Instrucciones", instrucciones), New ObjectParameter("Instrucciones", GetType(Boolean)))

        Dim distribucionParameter As ObjectParameter = If(distribucion.HasValue, New ObjectParameter("Distribucion", distribucion), New ObjectParameter("Distribucion", GetType(Boolean)))

        Dim nivelConfianzaParameter As ObjectParameter = If(nivelConfianza.HasValue, New ObjectParameter("NivelConfianza", nivelConfianza), New ObjectParameter("NivelConfianza", GetType(Boolean)))

        Dim margenErrorParameter As ObjectParameter = If(margenError.HasValue, New ObjectParameter("MargenError", margenError), New ObjectParameter("MargenError", GetType(Boolean)))

        Dim desagregacionParameter As ObjectParameter = If(desagregacion.HasValue, New ObjectParameter("Desagregacion", desagregacion), New ObjectParameter("Desagregacion", GetType(Boolean)))

        Dim fuenteParameter As ObjectParameter = If(fuente.HasValue, New ObjectParameter("Fuente", fuente), New ObjectParameter("Fuente", GetType(Boolean)))

        Dim variablesParameter As ObjectParameter = If(variables.HasValue, New ObjectParameter("Variables", variables), New ObjectParameter("Variables", GetType(Boolean)))

        Dim tasaParameter As ObjectParameter = If(tasa.HasValue, New ObjectParameter("Tasa", tasa), New ObjectParameter("Tasa", GetType(Boolean)))

        Dim procedimientoParameter As ObjectParameter = If(procedimiento.HasValue, New ObjectParameter("Procedimiento", procedimiento), New ObjectParameter("Procedimiento", GetType(Boolean)))

        Dim objetivoTParameter As ObjectParameter = If(objetivoT IsNot Nothing, New ObjectParameter("ObjetivoT", objetivoT), New ObjectParameter("ObjetivoT", GetType(String)))

        Dim mercadoTParameter As ObjectParameter = If(mercadoT IsNot Nothing, New ObjectParameter("MercadoT", mercadoT), New ObjectParameter("MercadoT", GetType(String)))

        Dim marcoTParameter As ObjectParameter = If(marcoT IsNot Nothing, New ObjectParameter("MarcoT", marcoT), New ObjectParameter("MarcoT", GetType(String)))

        Dim tecnicaTParameter As ObjectParameter = If(tecnicaT IsNot Nothing, New ObjectParameter("TecnicaT", tecnicaT), New ObjectParameter("TecnicaT", GetType(String)))

        Dim disenoTParameter As ObjectParameter = If(disenoT IsNot Nothing, New ObjectParameter("DisenoT", disenoT), New ObjectParameter("DisenoT", GetType(String)))

        Dim instruccionesTParameter As ObjectParameter = If(instruccionesT IsNot Nothing, New ObjectParameter("InstruccionesT", instruccionesT), New ObjectParameter("InstruccionesT", GetType(String)))

        Dim distribucionTParameter As ObjectParameter = If(distribucionT IsNot Nothing, New ObjectParameter("DistribucionT", distribucionT), New ObjectParameter("DistribucionT", GetType(String)))

        Dim nivelConfianzaTParameter As ObjectParameter = If(nivelConfianzaT IsNot Nothing, New ObjectParameter("NivelConfianzaT", nivelConfianzaT), New ObjectParameter("NivelConfianzaT", GetType(String)))

        Dim margenErrorTParameter As ObjectParameter = If(margenErrorT IsNot Nothing, New ObjectParameter("MargenErrorT", margenErrorT), New ObjectParameter("MargenErrorT", GetType(String)))

        Dim desagregacionTParameter As ObjectParameter = If(desagregacionT IsNot Nothing, New ObjectParameter("DesagregacionT", desagregacionT), New ObjectParameter("DesagregacionT", GetType(String)))

        Dim fuenteTParameter As ObjectParameter = If(fuenteT IsNot Nothing, New ObjectParameter("FuenteT", fuenteT), New ObjectParameter("FuenteT", GetType(String)))

        Dim variablesTParameter As ObjectParameter = If(variablesT IsNot Nothing, New ObjectParameter("VariablesT", variablesT), New ObjectParameter("VariablesT", GetType(String)))

        Dim tasaTParameter As ObjectParameter = If(tasaT IsNot Nothing, New ObjectParameter("TasaT", tasaT), New ObjectParameter("TasaT", GetType(String)))

        Dim procedimientoTParameter As ObjectParameter = If(procedimientoT IsNot Nothing, New ObjectParameter("ProcedimientoT", procedimientoT), New ObjectParameter("ProcedimientoT", GetType(String)))

        Dim versionParameter As ObjectParameter = If(version.HasValue, New ObjectParameter("Version", version), New ObjectParameter("Version", GetType(Byte)))

        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Decimal))("ES_MetodologiaCampo_Add", trabajoIdParameter, nombreEstudioParameter, fechaParameter, objetivoParameter, mercadoParameter, marcoParameter, tecnicaParameter, disenoParameter, instruccionesParameter, distribucionParameter, nivelConfianzaParameter, margenErrorParameter, desagregacionParameter, fuenteParameter, variablesParameter, tasaParameter, procedimientoParameter, objetivoTParameter, mercadoTParameter, marcoTParameter, tecnicaTParameter, disenoTParameter, instruccionesTParameter, distribucionTParameter, nivelConfianzaTParameter, margenErrorTParameter, desagregacionTParameter, fuenteTParameter, variablesTParameter, tasaTParameter, procedimientoTParameter, versionParameter, usuarioParameter)
    End Function

    Public Overridable Function ES_MetodologiaCampo_Edit(id As Nullable(Of Long), trabajoId As Nullable(Of Long), nombreEstudio As String, fecha As Nullable(Of Date), objetivo As Nullable(Of Boolean), mercado As Nullable(Of Boolean), marco As Nullable(Of Boolean), tecnica As Nullable(Of Boolean), diseno As Nullable(Of Boolean), instrucciones As Nullable(Of Boolean), distribucion As Nullable(Of Boolean), nivelConfianza As Nullable(Of Boolean), margenError As Nullable(Of Boolean), desagregacion As Nullable(Of Boolean), fuente As Nullable(Of Boolean), variables As Nullable(Of Boolean), tasa As Nullable(Of Boolean), procedimiento As Nullable(Of Boolean), objetivoT As String, mercadoT As String, marcoT As String, tecnicaT As String, disenoT As String, instruccionesT As String, distribucionT As String, nivelConfianzaT As String, margenErrorT As String, desagregacionT As String, fuenteT As String, variablesT As String, tasaT As String, procedimientoT As String) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim nombreEstudioParameter As ObjectParameter = If(nombreEstudio IsNot Nothing, New ObjectParameter("NombreEstudio", nombreEstudio), New ObjectParameter("NombreEstudio", GetType(String)))

        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("Fecha", fecha), New ObjectParameter("Fecha", GetType(Date)))

        Dim objetivoParameter As ObjectParameter = If(objetivo.HasValue, New ObjectParameter("Objetivo", objetivo), New ObjectParameter("Objetivo", GetType(Boolean)))

        Dim mercadoParameter As ObjectParameter = If(mercado.HasValue, New ObjectParameter("Mercado", mercado), New ObjectParameter("Mercado", GetType(Boolean)))

        Dim marcoParameter As ObjectParameter = If(marco.HasValue, New ObjectParameter("Marco", marco), New ObjectParameter("Marco", GetType(Boolean)))

        Dim tecnicaParameter As ObjectParameter = If(tecnica.HasValue, New ObjectParameter("Tecnica", tecnica), New ObjectParameter("Tecnica", GetType(Boolean)))

        Dim disenoParameter As ObjectParameter = If(diseno.HasValue, New ObjectParameter("Diseno", diseno), New ObjectParameter("Diseno", GetType(Boolean)))

        Dim instruccionesParameter As ObjectParameter = If(instrucciones.HasValue, New ObjectParameter("Instrucciones", instrucciones), New ObjectParameter("Instrucciones", GetType(Boolean)))

        Dim distribucionParameter As ObjectParameter = If(distribucion.HasValue, New ObjectParameter("Distribucion", distribucion), New ObjectParameter("Distribucion", GetType(Boolean)))

        Dim nivelConfianzaParameter As ObjectParameter = If(nivelConfianza.HasValue, New ObjectParameter("NivelConfianza", nivelConfianza), New ObjectParameter("NivelConfianza", GetType(Boolean)))

        Dim margenErrorParameter As ObjectParameter = If(margenError.HasValue, New ObjectParameter("MargenError", margenError), New ObjectParameter("MargenError", GetType(Boolean)))

        Dim desagregacionParameter As ObjectParameter = If(desagregacion.HasValue, New ObjectParameter("Desagregacion", desagregacion), New ObjectParameter("Desagregacion", GetType(Boolean)))

        Dim fuenteParameter As ObjectParameter = If(fuente.HasValue, New ObjectParameter("Fuente", fuente), New ObjectParameter("Fuente", GetType(Boolean)))

        Dim variablesParameter As ObjectParameter = If(variables.HasValue, New ObjectParameter("Variables", variables), New ObjectParameter("Variables", GetType(Boolean)))

        Dim tasaParameter As ObjectParameter = If(tasa.HasValue, New ObjectParameter("Tasa", tasa), New ObjectParameter("Tasa", GetType(Boolean)))

        Dim procedimientoParameter As ObjectParameter = If(procedimiento.HasValue, New ObjectParameter("Procedimiento", procedimiento), New ObjectParameter("Procedimiento", GetType(Boolean)))

        Dim objetivoTParameter As ObjectParameter = If(objetivoT IsNot Nothing, New ObjectParameter("ObjetivoT", objetivoT), New ObjectParameter("ObjetivoT", GetType(String)))

        Dim mercadoTParameter As ObjectParameter = If(mercadoT IsNot Nothing, New ObjectParameter("MercadoT", mercadoT), New ObjectParameter("MercadoT", GetType(String)))

        Dim marcoTParameter As ObjectParameter = If(marcoT IsNot Nothing, New ObjectParameter("MarcoT", marcoT), New ObjectParameter("MarcoT", GetType(String)))

        Dim tecnicaTParameter As ObjectParameter = If(tecnicaT IsNot Nothing, New ObjectParameter("TecnicaT", tecnicaT), New ObjectParameter("TecnicaT", GetType(String)))

        Dim disenoTParameter As ObjectParameter = If(disenoT IsNot Nothing, New ObjectParameter("DisenoT", disenoT), New ObjectParameter("DisenoT", GetType(String)))

        Dim instruccionesTParameter As ObjectParameter = If(instruccionesT IsNot Nothing, New ObjectParameter("InstruccionesT", instruccionesT), New ObjectParameter("InstruccionesT", GetType(String)))

        Dim distribucionTParameter As ObjectParameter = If(distribucionT IsNot Nothing, New ObjectParameter("DistribucionT", distribucionT), New ObjectParameter("DistribucionT", GetType(String)))

        Dim nivelConfianzaTParameter As ObjectParameter = If(nivelConfianzaT IsNot Nothing, New ObjectParameter("NivelConfianzaT", nivelConfianzaT), New ObjectParameter("NivelConfianzaT", GetType(String)))

        Dim margenErrorTParameter As ObjectParameter = If(margenErrorT IsNot Nothing, New ObjectParameter("MargenErrorT", margenErrorT), New ObjectParameter("MargenErrorT", GetType(String)))

        Dim desagregacionTParameter As ObjectParameter = If(desagregacionT IsNot Nothing, New ObjectParameter("DesagregacionT", desagregacionT), New ObjectParameter("DesagregacionT", GetType(String)))

        Dim fuenteTParameter As ObjectParameter = If(fuenteT IsNot Nothing, New ObjectParameter("FuenteT", fuenteT), New ObjectParameter("FuenteT", GetType(String)))

        Dim variablesTParameter As ObjectParameter = If(variablesT IsNot Nothing, New ObjectParameter("VariablesT", variablesT), New ObjectParameter("VariablesT", GetType(String)))

        Dim tasaTParameter As ObjectParameter = If(tasaT IsNot Nothing, New ObjectParameter("TasaT", tasaT), New ObjectParameter("TasaT", GetType(String)))

        Dim procedimientoTParameter As ObjectParameter = If(procedimientoT IsNot Nothing, New ObjectParameter("ProcedimientoT", procedimientoT), New ObjectParameter("ProcedimientoT", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ES_MetodologiaCampo_Edit", idParameter, trabajoIdParameter, nombreEstudioParameter, fechaParameter, objetivoParameter, mercadoParameter, marcoParameter, tecnicaParameter, disenoParameter, instruccionesParameter, distribucionParameter, nivelConfianzaParameter, margenErrorParameter, desagregacionParameter, fuenteParameter, variablesParameter, tasaParameter, procedimientoParameter, objetivoTParameter, mercadoTParameter, marcoTParameter, tecnicaTParameter, disenoTParameter, instruccionesTParameter, distribucionTParameter, nivelConfianzaTParameter, margenErrorTParameter, desagregacionTParameter, fuenteTParameter, variablesTParameter, tasaTParameter, procedimientoTParameter)
    End Function

    Public Overridable Function ES_MetodologiaCampo_Del(id As Nullable(Of Long)) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ES_MetodologiaCampo_Del", idParameter)
    End Function

    Public Overridable Function ES_BriefDisenoMuestral_Del(id As Nullable(Of Long)) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ES_BriefDisenoMuestral_Del", idParameter)
    End Function

    Public Overridable Function ES_DisenoMuestral_Del(id As Nullable(Of Long)) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ES_DisenoMuestral_Del", idParameter)
    End Function

    Public Overridable Function ES_MetodologiaCampo_Get(id As Nullable(Of Long), trabajoId As Nullable(Of Long)) As ObjectResult(Of ES_MetodologiaCampo_Get_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ES_MetodologiaCampo_Get_Result)("ES_MetodologiaCampo_Get", idParameter, trabajoIdParameter)
    End Function

    Public Overridable Function ES_MetodologiaCampoTr(trabajo As Nullable(Of Integer)) As ObjectResult(Of ES_MetodologiaCampoTr_Result)
        Dim trabajoParameter As ObjectParameter = If(trabajo.HasValue, New ObjectParameter("Trabajo", trabajo), New ObjectParameter("Trabajo", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ES_MetodologiaCampoTr_Result)("ES_MetodologiaCampoTr", trabajoParameter)
    End Function

    Public Overridable Function ES_ObtenerMetodologiaXIdxTr(trabajoId As Nullable(Of Integer), id As Nullable(Of Integer)) As ObjectResult(Of ES_ObtenerMetodologiaXIdxTr_Result)
        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Integer)))

        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ES_ObtenerMetodologiaXIdxTr_Result)("ES_ObtenerMetodologiaXIdxTr", trabajoIdParameter, idParameter)
    End Function

    Public Overridable Function ES_MetodologiaCampo_NumVersiones(idTrabajo As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Integer))
        Dim idTrabajoParameter As ObjectParameter = If(idTrabajo.HasValue, New ObjectParameter("idTrabajo", idTrabajo), New ObjectParameter("idTrabajo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("ES_MetodologiaCampo_NumVersiones", idTrabajoParameter)
    End Function

    Public Overridable Function ES_DisenoMuestral_Get(id As Nullable(Of Long), briefId As Nullable(Of Long)) As ObjectResult(Of ES_DisenoMuestral_Get_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Long)))

        Dim briefIdParameter As ObjectParameter = If(briefId.HasValue, New ObjectParameter("BriefId", briefId), New ObjectParameter("BriefId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ES_DisenoMuestral_Get_Result)("ES_DisenoMuestral_Get", idParameter, briefIdParameter)
    End Function

    Public Overridable Function ES_BriefDisenoMuestral_Get(id As Nullable(Of Long), propuestaId As Nullable(Of Long)) As ObjectResult(Of ES_BriefDisenoMuestral_Get_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Long)))

        Dim propuestaIdParameter As ObjectParameter = If(propuestaId.HasValue, New ObjectParameter("PropuestaId", propuestaId), New ObjectParameter("PropuestaId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ES_BriefDisenoMuestral_Get_Result)("ES_BriefDisenoMuestral_Get", idParameter, propuestaIdParameter)
    End Function

End Class
