'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GD_SolicitudDocumentos
    Public Property Id As Long
    Public Property FechaSolicitud As Date
    Public Property Solicitante As Nullable(Of Long)
    Public Property Area As String
    Public Property Cargo As String
    Public Property Tipoid As Integer
    Public Property DocumentoId As Nullable(Of Long)
    Public Property NombreDocumento As String
    Public Property Codigo As String
    Public Property AreaUso As String
    Public Property SitioAcceso As String
    Public Property RazonSolicitud As String
    Public Property DescripcionSolicitud As String
    Public Property Estadoid As Nullable(Of Byte)
    Public Property FechaEstado As Nullable(Of Date)
    Public Property Comentarios As String
    Public Property Modificacion As String

    Public Overridable Property GD_EstadoSolicitud As GD_EstadoSolicitud
    Public Overridable Property GD_MaestroDocumentos As GD_MaestroDocumentos
    Public Overridable Property GD_TipoSolicitud As GD_TipoSolicitud

End Class
