'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IQ_AnalisisEstadisticaPresupuesto
    Public Property IdPropuesta As Long
    Public Property ParAlternativa As Integer
    Public Property MetCodigo As Integer
    Public Property ParNacional As Integer
    Public Property IdAnalisis As Integer
    Public Property Cantidad As Integer
    Public Property VrTotal As Nullable(Of Double)
    Public Property Factor As Nullable(Of Double)

End Class
