'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IQ_Actividades
    Public Property ID As Integer
    Public Property ActNombre As String
    Public Property ProcCodigo As Integer
    Public Property MetCodigo As Integer
    Public Property ActAAI As String
    Public Property ActJobStep As Nullable(Of Integer)
    Public Property ActJobActividad As Nullable(Of Integer)
    Public Property ActTipoCalculo As String
    Public Property ActSubcontratada As Nullable(Of Boolean)
    Public Property ActTipoValor As String
    Public Property AplicaGM As Nullable(Of Boolean)
    Public Property Area As Nullable(Of Integer)
    Public Property iQuoteName As String
    Public Property TypeIQuote As String
    Public Property OrderIQuote As Nullable(Of Byte)

    Public Overridable Property IQ_TecnicasActividades As ICollection(Of IQ_TecnicasActividades) = New HashSet(Of IQ_TecnicasActividades)

End Class
