'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IQ_Ciudades
    Public Property CiuPais As Nullable(Of Integer)
    Public Property CiuDep As Nullable(Of Integer)
    Public Property CiuCiudad As Integer
    Public Property CiuOrden As Nullable(Of Double)
    Public Property CiuNombre As String
    Public Property CiuCategoria As Nullable(Of Double)
    Public Property CiuSede As Boolean
    Public Property CiuResponsable As Nullable(Of Double)
    Public Property CiuDependencia As Nullable(Of Double)
    Public Property CiuReqSupervision As Boolean
    Public Property CiuDistanciaKM As Nullable(Of Integer)
    Public Property CiuDistanciaTp As Nullable(Of Double)
    Public Property CiuTipoTransp As String
    Public Property CiuTransporte As Nullable(Of Decimal)
    Public Property CiuTransAereoBta As Nullable(Of Decimal)
    Public Property CiuTransUrbanoBus As Nullable(Of Decimal)
    Public Property CiuTransUrbanoTaxi As Nullable(Of Decimal)
    Public Property CiuTransAeropCiudad As Nullable(Of Decimal)
    Public Property CiuEnvioNormal As Nullable(Of Decimal)
    Public Property CiuEnvioDiario As Nullable(Of Decimal)
    Public Property CiuImpAeroportuario As Nullable(Of Decimal)
    Public Property CiuDeptoNombre As String
    Public Property CiuHotelCategoria1 As Nullable(Of Decimal)
    Public Property CiuHotelCategoria2 As Nullable(Of Decimal)
    Public Property CiuAlimentacionDia As Nullable(Of Decimal)

End Class
