'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IQ_ParametrosGenerales
    Public Property PGrGrupo As Integer
    Public Property PGrCodigo As Integer
    Public Property PGrDescripcion As String
    Public Property PGrValor1 As Nullable(Of Single)
    Public Property PGrValor2 As Nullable(Of Single)
    Public Property PGrResponsable As Nullable(Of Integer)
    Public Property PGrObservaciones As String
    Public Property PGrFecActualiza As Nullable(Of Date)
    Public Property PGrFecVigencia As Nullable(Of Date)

End Class
