'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IQ_SolicitudesAjustesPresupuesto
    Public Property id As Long
    Public Property IdPropuesta As Long
    Public Property ParAlternativa As Integer
    Public Property MetCodigo As Integer
    Public Property ParNacional As Integer
    Public Property TipoSolicitud As Integer
    Public Property ValorVenta As Long
    Public Property GM As Double
    Public Property OP As Double
    Public Property GMOPS As Double
    Public Property SolicitadoPor As Long
    Public Property FechaSolicitud As Date
    Public Property AprobadoPor As Nullable(Of Long)
    Public Property FechaAprobacion As Nullable(Of Date)
    Public Property Aprobado As Nullable(Of Boolean)
    Public Property ComentariosSolicitud As String
    Public Property ComentariosAprobacion As String

End Class
