'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IQ_Tecnicas
    Public Property TecCodigo As String
    Public Property TecDescripcion As String
    Public Property TecOrden As Integer
    Public Property TecMetodologia As Integer

End Class
