'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IQ_TarifasEstadistica
    Public Property IdAnalisis As Integer
    Public Property Categoria As String
    Public Property AnalisisServicio As String
    Public Property EspecificacionesEntregable As String
    Public Property HorasEstimadas As Nullable(Of Decimal)
    Public Property Precio As Nullable(Of Double)
    Public Property FactorEscala As Nullable(Of Double)
    Public Property TiempoEstimado As String
    Public Property Orden As Nullable(Of Integer)
    Public Property Activo As Nullable(Of Boolean)

End Class
