'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IQ_ValorVisitaMistery
    Public Property TM_Id As Decimal
    Public Property VM_Id As Integer
    Public Property IdPropuesta As Long
    Public Property ParAlternativa As Integer
    Public Property MetCodigo As Integer
    Public Property ParNacional As Integer
    Public Property TM_Valor As Decimal
    Public Property TE_TiempoCritica As Nullable(Of Integer)

    Public Overridable Property IQ_TarifasMistery As IQ_TarifasMistery

End Class
