'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class OP_Cuanti2
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=OP_Cuanti2")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property C_Divipola() As DbSet(Of C_Divipola2)
    Public Overridable Property OP_TipoEncuestador() As DbSet(Of OP_TipoEncuestador)
    Public Overridable Property PY_Trabajo() As DbSet(Of PY_Trabajo2)
    Public Overridable Property TH_Capacitaciones() As DbSet(Of TH_Capacitaciones)
    Public Overridable Property TH_CapacitacionesParticipantes() As DbSet(Of TH_CapacitacionesParticipantes)
    Public Overridable Property TH_Cargos() As DbSet(Of TH_Cargos)
    Public Overridable Property TH_Personas() As DbSet(Of TH_Personas)
    Public Overridable Property TH_TipoContratacion() As DbSet(Of TH_TipoContratacion)
    Public Overridable Property OP_Encuestadores() As DbSet(Of OP_Encuestadores)
    Public Overridable Property OP_PersonasAsignadasTrabajo() As DbSet(Of OP_PersonasAsignadasTrabajo)

    Public Overridable Function OP_PersonasAsignadasTrabajo_Get(trabajoId As Nullable(Of Long), cargoId As Nullable(Of Long), ciudad As Nullable(Of Long)) As ObjectResult(Of OP_PersonasAsignacion_Result)
        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim cargoIdParameter As ObjectParameter = If(cargoId.HasValue, New ObjectParameter("CargoId", cargoId), New ObjectParameter("CargoId", GetType(Long)))

        Dim ciudadParameter As ObjectParameter = If(ciudad.HasValue, New ObjectParameter("Ciudad", ciudad), New ObjectParameter("Ciudad", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_PersonasAsignacion_Result)("OP_PersonasAsignadasTrabajo_Get", trabajoIdParameter, cargoIdParameter, ciudadParameter)
    End Function

    Public Overridable Function OP_PersonasCapacitadasSinAsignadarTrabajo_Get(trabajoId As Nullable(Of Long), cargoId As Nullable(Of Long), ciudad As Nullable(Of Long)) As ObjectResult(Of OP_PersonasAsignacion_Result)
        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim cargoIdParameter As ObjectParameter = If(cargoId.HasValue, New ObjectParameter("CargoId", cargoId), New ObjectParameter("CargoId", GetType(Long)))

        Dim ciudadParameter As ObjectParameter = If(ciudad.HasValue, New ObjectParameter("Ciudad", ciudad), New ObjectParameter("Ciudad", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_PersonasAsignacion_Result)("OP_PersonasCapacitadasSinAsignadarTrabajo_Get", trabajoIdParameter, cargoIdParameter, ciudadParameter)
    End Function

    Public Overridable Function OP_ListadoPersonasAsignadasTrabajo(trabajoid As Nullable(Of Long)) As ObjectResult(Of OP_ListadoPersonasAsignadasTrabajo_Result)
        Dim trabajoidParameter As ObjectParameter = If(trabajoid.HasValue, New ObjectParameter("trabajoid", trabajoid), New ObjectParameter("trabajoid", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_ListadoPersonasAsignadasTrabajo_Result)("OP_ListadoPersonasAsignadasTrabajo", trabajoidParameter)
    End Function

    Public Overridable Function OP_PersonalSinProduccion(fecha As Nullable(Of Date), cargo As Nullable(Of Long)) As ObjectResult(Of OP_PersonalSinProduccion_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim cargoParameter As ObjectParameter = If(cargo.HasValue, New ObjectParameter("cargo", cargo), New ObjectParameter("cargo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_PersonalSinProduccion_Result)("OP_PersonalSinProduccion", fechaParameter, cargoParameter)
    End Function

End Class
