'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_CampoCuali
    Public Property id As Long
    Public Property SegmentoId As Nullable(Of Long)
    Public Property Moderador As Nullable(Of Long)
    Public Property PlaneacionPor As Nullable(Of Long)
    Public Property Lugar As String
    Public Property PersonaContaco As String
    Public Property DatosContacto As String
    Public Property Direccion As String
    Public Property Fecha As Nullable(Of Date)
    Public Property Hora As Nullable(Of System.TimeSpan)
    Public Property ObservacionesPrevias As String
    Public Property FechaReal As Nullable(Of Date)
    Public Property HoraReal As Nullable(Of System.TimeSpan)
    Public Property Asistentes As Nullable(Of Integer)
    Public Property AsistentesNoCumplen As Nullable(Of Integer)
    Public Property ObservacionesEjecucion As String
    Public Property EjecucionPor As Nullable(Of Long)
    Public Property Caida As Nullable(Of Boolean)
    Public Property Cancelada As Nullable(Of Boolean)
    Public Property Ejecutada As Nullable(Of Boolean)
    Public Property Transcriptor As Nullable(Of Long)

    Public Overridable Property PY_SegmentosCuali As PY_SegmentosCuali

End Class
