
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("41d2e904-47b8-4e55-8b7c-ccefe124ddd0")>

#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Partial Public Class OP_Q_Entities
    Inherits ObjectContext

#Region "Constructors"

    ''' <summary>
    ''' Inicializa un nuevo objeto OP_CuantiContainer usando la cadena de conexión encontrada en la sección 'OP_CuantiContainer' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=OP_Q_Entities", "OP_Q_Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = True
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto OP_CuantiContainer.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "OP_Q_Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = True
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto OP_CuantiContainer.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "OP_Q_Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = True
        OnContextCreated()
    End Sub

#End Region

#Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

#End Region

#Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property OP_FichaCuantitativo() As ObjectSet(Of OP_FichaCuantitativo)
        Get
            If (_OP_FichaCuantitativo Is Nothing) Then
                _OP_FichaCuantitativo = MyBase.CreateObjectSet(Of OP_FichaCuantitativo)("OP_FichaCuantitativo")
            End If
            Return _OP_FichaCuantitativo
        End Get
    End Property

    Private _OP_FichaCuantitativo As ObjectSet(Of OP_FichaCuantitativo)

#End Region
#Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet OP_FichaCuantitativo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToOP_FichaCuantitativo(ByVal oP_FichaCuantitativo As OP_FichaCuantitativo)
        MyBase.AddObject("OP_FichaCuantitativo", oP_FichaCuantitativo)
    End Sub

#End Region
End Class

#End Region
#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="OP_Cuanti", Name:="OP_FichaCuantitativo")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class OP_FichaCuantitativo
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto OP_FichaCuantitativo.
    ''' </summary>
    ''' <param name="id">Valor inicial de la propiedad id.</param>
    Public Shared Function CreateOP_FichaCuantitativo(id As Global.System.Int64) As OP_FichaCuantitativo
        Dim oP_FichaCuantitativo as OP_FichaCuantitativo = New OP_FichaCuantitativo
        oP_FichaCuantitativo.id = id
        Return oP_FichaCuantitativo
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int64
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int64
    Private Partial Sub OnidChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TrabajoId() As Nullable(Of Global.System.Int64)
        Get
            Return _TrabajoId
        End Get
        Set
            OnTrabajoIdChanging(value)
            ReportPropertyChanging("TrabajoId")
            _TrabajoId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TrabajoId")
            OnTrabajoIdChanged()
        End Set
    End Property

    Private _TrabajoId As Nullable(Of Global.System.Int64)
    Private Partial Sub OnTrabajoIdChanging(value As Nullable(Of Global.System.Int64))
    End Sub

    Private Partial Sub OnTrabajoIdChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property GrupoObjetivo() As Global.System.String
        Get
            Return _GrupoObjetivo
        End Get
        Set
            OnGrupoObjetivoChanging(value)
            ReportPropertyChanging("GrupoObjetivo")
            _GrupoObjetivo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("GrupoObjetivo")
            OnGrupoObjetivoChanged()
        End Set
    End Property

    Private _GrupoObjetivo As Global.System.String
    Private Partial Sub OnGrupoObjetivoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGrupoObjetivoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CubrimientoGeografico() As Global.System.String
        Get
            Return _CubrimientoGeografico
        End Get
        Set
            OnCubrimientoGeograficoChanging(value)
            ReportPropertyChanging("CubrimientoGeografico")
            _CubrimientoGeografico = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CubrimientoGeografico")
            OnCubrimientoGeograficoChanged()
        End Set
    End Property

    Private _CubrimientoGeografico As Global.System.String
    Private Partial Sub OnCubrimientoGeograficoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCubrimientoGeograficoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MarcoMuestral() As Global.System.String
        Get
            Return _MarcoMuestral
        End Get
        Set
            OnMarcoMuestralChanging(value)
            ReportPropertyChanging("MarcoMuestral")
            _MarcoMuestral = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MarcoMuestral")
            OnMarcoMuestralChanged()
        End Set
    End Property

    Private _MarcoMuestral As Global.System.String
    Private Partial Sub OnMarcoMuestralChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMarcoMuestralChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DistribucionMuestra() As Global.System.String
        Get
            Return _DistribucionMuestra
        End Get
        Set
            OnDistribucionMuestraChanging(value)
            ReportPropertyChanging("DistribucionMuestra")
            _DistribucionMuestra = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DistribucionMuestra")
            OnDistribucionMuestraChanged()
        End Set
    End Property

    Private _DistribucionMuestra As Global.System.String
    Private Partial Sub OnDistribucionMuestraChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDistribucionMuestraChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Cuotas() As Global.System.String
        Get
            Return _Cuotas
        End Get
        Set
            OnCuotasChanging(value)
            ReportPropertyChanging("Cuotas")
            _Cuotas = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Cuotas")
            OnCuotasChanged()
        End Set
    End Property

    Private _Cuotas As Global.System.String
    Private Partial Sub OnCuotasChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCuotasChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NivelDesagregacionResultados() As Global.System.String
        Get
            Return _NivelDesagregacionResultados
        End Get
        Set
            OnNivelDesagregacionResultadosChanging(value)
            ReportPropertyChanging("NivelDesagregacionResultados")
            _NivelDesagregacionResultados = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NivelDesagregacionResultados")
            OnNivelDesagregacionResultadosChanged()
        End Set
    End Property

    Private _NivelDesagregacionResultados As Global.System.String
    Private Partial Sub OnNivelDesagregacionResultadosChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNivelDesagregacionResultadosChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Ponderacion() As Global.System.String
        Get
            Return _Ponderacion
        End Get
        Set
            OnPonderacionChanging(value)
            ReportPropertyChanging("Ponderacion")
            _Ponderacion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Ponderacion")
            OnPonderacionChanged()
        End Set
    End Property

    Private _Ponderacion As Global.System.String
    Private Partial Sub OnPonderacionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPonderacionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RequerimientosEspeciales() As Global.System.String
        Get
            Return _RequerimientosEspeciales
        End Get
        Set
            OnRequerimientosEspecialesChanging(value)
            ReportPropertyChanging("RequerimientosEspeciales")
            _RequerimientosEspeciales = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("RequerimientosEspeciales")
            OnRequerimientosEspecialesChanged()
        End Set
    End Property

    Private _RequerimientosEspeciales As Global.System.String
    Private Partial Sub OnRequerimientosEspecialesChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRequerimientosEspecialesChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property OtrasObservaciones() As Global.System.String
        Get
            Return _OtrasObservaciones
        End Get
        Set
            OnOtrasObservacionesChanging(value)
            ReportPropertyChanging("OtrasObservaciones")
            _OtrasObservaciones = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("OtrasObservaciones")
            OnOtrasObservacionesChanged()
        End Set
    End Property

    Private _OtrasObservaciones As Global.System.String
    Private Partial Sub OnOtrasObservacionesChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOtrasObservacionesChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IncentivoEconomico() As Nullable(Of Global.System.Boolean)
        Get
            Return _IncentivoEconomico
        End Get
        Set
            OnIncentivoEconomicoChanging(value)
            ReportPropertyChanging("IncentivoEconomico")
            _IncentivoEconomico = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IncentivoEconomico")
            OnIncentivoEconomicoChanged()
        End Set
    End Property

    Private _IncentivoEconomico As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnIncentivoEconomicoChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnIncentivoEconomicoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PresupuestoIncentivo() As Nullable(Of Global.System.Double)
        Get
            Return _PresupuestoIncentivo
        End Get
        Set
            OnPresupuestoIncentivoChanging(value)
            ReportPropertyChanging("PresupuestoIncentivo")
            _PresupuestoIncentivo = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PresupuestoIncentivo")
            OnPresupuestoIncentivoChanged()
        End Set
    End Property

    Private _PresupuestoIncentivo As Nullable(Of Global.System.Double)
    Private Partial Sub OnPresupuestoIncentivoChanging(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub OnPresupuestoIncentivoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RegalosCliente() As Nullable(Of Global.System.Boolean)
        Get
            Return _RegalosCliente
        End Get
        Set
            OnRegalosClienteChanging(value)
            ReportPropertyChanging("RegalosCliente")
            _RegalosCliente = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("RegalosCliente")
            OnRegalosClienteChanged()
        End Set
    End Property

    Private _RegalosCliente As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnRegalosClienteChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnRegalosClienteChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CompraIpsos() As Nullable(Of Global.System.Boolean)
        Get
            Return _CompraIpsos
        End Get
        Set
            OnCompraIpsosChanging(value)
            ReportPropertyChanging("CompraIpsos")
            _CompraIpsos = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CompraIpsos")
            OnCompraIpsosChanged()
        End Set
    End Property

    Private _CompraIpsos As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnCompraIpsosChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnCompraIpsosChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Presupuesto() As Nullable(Of Global.System.Double)
        Get
            Return _Presupuesto
        End Get
        Set
            OnPresupuestoChanging(value)
            ReportPropertyChanging("Presupuesto")
            _Presupuesto = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Presupuesto")
            OnPresupuestoChanged()
        End Set
    End Property

    Private _Presupuesto As Nullable(Of Global.System.Double)
    Private Partial Sub OnPresupuestoChanging(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub OnPresupuestoChanged()
    End Sub

    #End Region
End Class

#End Region

