'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_Encuestadores4
    Public Property id As Long
    Public Property TipoId As Nullable(Of Byte)
    Public Property Vetado As Nullable(Of Boolean)
    Public Property FechaVetado As Nullable(Of Date)
    Public Property VetadoPor As Nullable(Of Long)
    Public Property RazonVeto As String

    Public Overridable Property OP_TipoEncuestador As OP_TipoEncuestador4
    Public Overridable Property TH_Personas As TH_Personas2

End Class
