'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_EstimacionesProduccionCiudad
    Public Property id As Long
    Public Property TrabajoId As Nullable(Of Long)
    Public Property FechaEstimacion As Nullable(Of Date)
    Public Property CiudadId As Nullable(Of Integer)
    Public Property UsuarioEstimacion As Nullable(Of Long)
    Public Property Observaciones As String
    Public Property Bloqueada As Nullable(Of Boolean)
    Public Property Activa As Nullable(Of Boolean)

    Public Overridable Property C_Divipola As C_Divipola
    Public Overridable Property OP_TrabajoConfiguracion As OP_TrabajoConfiguracion
    Public Overridable Property OP_EstimacionProduccion As ICollection(Of OP_EstimacionProduccion) = New HashSet(Of OP_EstimacionProduccion)
    Public Overridable Property US_Usuarios As US_Usuarios2

End Class
