'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_EncuestasAnuladas
    Public Property id As Long
    Public Property TrabajoId As Long
    Public Property NumeroEncuesta As Long
    Public Property Observacion As String
    Public Property Fecha As Date
    Public Property UsuarioId As Long
    Public Property UnidadId As Integer

    Public Overridable Property US_Usuarios As US_Usuarios2
    Public Overridable Property TH_Personas As TH_Personas3
    Public Overridable Property US_Unidades As US_Unidades3

End Class
