'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_MuestraTrabajos
    Public Property Id As Long
    Public Property CiudadId As Nullable(Of Integer)
    Public Property TrabajoId As Nullable(Of Long)
    Public Property Cantidad As Nullable(Of Double)
    Public Property Coordinador As Nullable(Of Long)
    Public Property FechaInicio As Nullable(Of Date)
    Public Property FechaFin As Nullable(Of Date)

    Public Overridable Property C_Divipola As C_Divipola
    Public Overridable Property PY_Trabajo As PY_Trabajo

End Class
