'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_Observaciones_Programacion_Campo_Cuali
    Public Property id As Long
    Public Property TrabajoId As Long
    Public Property EntrevistadoId As Long
    Public Property Observador As String
    Public Property UsuarioCreacion As Nullable(Of Long)
    Public Property FechaCreacion As Nullable(Of Date)

    Public Overridable Property OP_Entrevistados_Cuali As OP_Entrevistados_Cuali

End Class
