'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_PersonasAsignadasTrabajo
    Public Property id As Long
    Public Property TrabajoId As Nullable(Of Long)
    Public Property Persona As Nullable(Of Long)
    Public Property Ciudad As Nullable(Of Integer)

    Public Overridable Property PY_Trabajo As PY_Trabajo2
    Public Overridable Property TH_Personas As TH_Personas

End Class
