'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_ProduccionEstimadaOPTrafico
    Public Property id As Long
    Public Property RMC As Nullable(Of Integer)
    Public Property Critica As Nullable(Of Integer)
    Public Property Verificacion As Nullable(Of Integer)
    Public Property Captura As Nullable(Of Integer)

    Public Overridable Property PY_Trabajo As PY_Trabajo

End Class
