'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_Tecnicas
    Public Property id As Integer
    Public Property TecCodigo As Integer
    Public Property TecNombre As String
    Public Property TecTipo As Nullable(Of Integer)
    Public Property GrupoUnidad As Nullable(Of Integer)

    Public Overridable Property OP_Metodologias As ICollection(Of OP_Metodologias) = New HashSet(Of OP_Metodologias)

End Class
