'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_TipoFiltro
    Public Property Id As Integer
    Public Property TipoFiltro As String

    Public Overridable Property OP_Filtros As ICollection(Of OP_Filtros) = New HashSet(Of OP_Filtros)

End Class
