'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OP_TipoEncuestador
    Public Property id As Byte
    Public Property Tipo As String

    Public Overridable Property OP_Encuestadores As ICollection(Of OP_Encuestadores) = New HashSet(Of OP_Encuestadores)

End Class
