'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PNC_ProductoNoConformeAcciones
    Public Property Id As Integer
    Public Property IdPNC As Nullable(Of Integer)
    Public Property IdCausa As Nullable(Of Integer)
    Public Property TipoAccion As Nullable(Of Integer)
    Public Property Accion As String
    Public Property FechaPlaneada As Nullable(Of Date)
    Public Property FechaEjecucion As Nullable(Of Date)
    Public Property IdResponsableAccion As Nullable(Of Integer)
    Public Property IdResponsableSeguimiento As Nullable(Of Integer)
    Public Property EvidenciaCierre As String
    Public Property PermiteActualizar As Nullable(Of Boolean)

End Class
