'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PNC_VerProductoNoConformeCausas
    Public Property JobBook As String
    Public Property IdPNC As Nullable(Of Integer)
    Public Property IdCausa As Integer
    Public Property CausaRaiz As String

End Class
