'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class PY_CualiEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PY_CualiEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property PY_AyudasCuali() As DbSet(Of PY_AyudasCuali)
    Public Overridable Property PY_LugaresCuali() As DbSet(Of PY_LugaresCuali)
    Public Overridable Property OP_CampoCuali() As DbSet(Of OP_CampoCuali)
    Public Overridable Property PY_SegmentosCuali() As DbSet(Of PY_SegmentosCuali)
    Public Overridable Property PY_SegmentosCuali_Moderadores() As DbSet(Of PY_SegmentosCuali_Moderadores)
    Public Overridable Property PY_SegmentosCuali_Reclutadores() As DbSet(Of PY_SegmentosCuali_Reclutadores)
    Public Overridable Property PY_AyudasRequeridasCuali() As DbSet(Of PY_AyudasRequeridasCuali)
    Public Overridable Property PY_TipoReclutamientoCuali() As DbSet(Of PY_TipoReclutamientoCuali)
    Public Overridable Property PY_ReclutamientoRequeridoCuali() As DbSet(Of PY_ReclutamientoRequeridoCuali)
    Public Overridable Property OP_EstadosSesion() As DbSet(Of OP_EstadosSesion)
    Public Overridable Property OP_LogSesionesCuali() As DbSet(Of OP_LogSesionesCuali)
    Public Overridable Property OP_LogInHomeCuali() As DbSet(Of OP_LogInHomeCuali)
    Public Overridable Property OP_EntrevistasCuali_Distribucion() As DbSet(Of OP_EntrevistasCuali_Distribucion)
    Public Overridable Property OP_LogEntrevistasCuali() As DbSet(Of OP_LogEntrevistasCuali)
    Public Overridable Property OP_Filtros() As DbSet(Of OP_Filtros)
    Public Overridable Property OP_Preguntas_Filtro() As DbSet(Of OP_Preguntas_Filtro)
    Public Overridable Property OP_TipoFiltro() As DbSet(Of OP_TipoFiltro)
    Public Overridable Property OP_TipoPregunta_Filtro() As DbSet(Of OP_TipoPregunta_Filtro)
    Public Overridable Property OP_Respuestas_Filtro_Detalle() As DbSet(Of OP_Respuestas_Filtro_Detalle)
    Public Overridable Property OP_Respuestas_Filtro_Maestro() As DbSet(Of OP_Respuestas_Filtro_Maestro)
    Public Overridable Property OP_LogRespuestas_Filtro() As DbSet(Of OP_LogRespuestas_Filtro)
    Public Overridable Property OP_MuestraTrabajosCuali_Entrevistas() As DbSet(Of OP_MuestraTrabajosCuali_Entrevistas)
    Public Overridable Property OP_MuestraTrabajosCuali_InHome() As DbSet(Of OP_MuestraTrabajosCuali_InHome)
    Public Overridable Property OP_MuestraTrabajosCuali_Sesiones() As DbSet(Of OP_MuestraTrabajosCuali_Sesiones)
    Public Overridable Property OP_MuestraTrabajosCuali() As DbSet(Of OP_MuestraTrabajosCuali)
    Public Overridable Property PY_EspCuentasCuali() As DbSet(Of PY_EspCuentasCuali)
    Public Overridable Property PY_EspecifTecTrabajoCuali() As DbSet(Of PY_EspecifTecTrabajoCuali)

    Public Overridable Function OP_CampoCuali_Get(segmentoID As Nullable(Of Long)) As ObjectResult(Of OP_CampoCuali_Get_Result)
        Dim segmentoIDParameter As ObjectParameter = If(segmentoID.HasValue, New ObjectParameter("SegmentoID", segmentoID), New ObjectParameter("SegmentoID", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_CampoCuali_Get_Result)("OP_CampoCuali_Get", segmentoIDParameter)
    End Function

    Public Overridable Function PY_SegmentosCuali_Get(tRABAJOID As Nullable(Of Long)) As ObjectResult(Of PY_SegmentosCuali_Get_Result)
        Dim tRABAJOIDParameter As ObjectParameter = If(tRABAJOID.HasValue, New ObjectParameter("TRABAJOID", tRABAJOID), New ObjectParameter("TRABAJOID", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PY_SegmentosCuali_Get_Result)("PY_SegmentosCuali_Get", tRABAJOIDParameter)
    End Function

    Public Overridable Function PY_SegmentosCualiDuplicar(idSegmento As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Decimal))
        Dim idSegmentoParameter As ObjectParameter = If(idSegmento.HasValue, New ObjectParameter("idSegmento", idSegmento), New ObjectParameter("idSegmento", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Decimal))("PY_SegmentosCualiDuplicar", idSegmentoParameter)
    End Function

    Public Overridable Function OP_CampoCualiDuplicar(idCampo As Nullable(Of Long)) As ObjectResult(Of Nullable(Of Decimal))
        Dim idCampoParameter As ObjectParameter = If(idCampo.HasValue, New ObjectParameter("idCampo", idCampo), New ObjectParameter("idCampo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Decimal))("OP_CampoCualiDuplicar", idCampoParameter)
    End Function

    Public Overridable Function OP_ListadoCampoCualiXSegmento(idSegmento As Nullable(Of Long)) As ObjectResult(Of OP_ListadoCampoCualiXSegmento_Result)
        Dim idSegmentoParameter As ObjectParameter = If(idSegmento.HasValue, New ObjectParameter("IdSegmento", idSegmento), New ObjectParameter("IdSegmento", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_ListadoCampoCualiXSegmento_Result)("OP_ListadoCampoCualiXSegmento", idSegmentoParameter)
    End Function

    Public Overridable Function US_UsuariosModeradoresCualitativos() As ObjectResult(Of US_UsuariosModeradoresCualitativos_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of US_UsuariosModeradoresCualitativos_Result)("US_UsuariosModeradoresCualitativos")
    End Function

    Public Overridable Function US_UsuariosReclutadoresCualitativos() As ObjectResult(Of US_UsuariosReclutadoresCualitativos_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of US_UsuariosReclutadoresCualitativos_Result)("US_UsuariosReclutadoresCualitativos")
    End Function

    Public Overridable Function US_UsuariosTranscriptoresCualitativos() As ObjectResult(Of US_UsuariosTranscriptoresCualitativos_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of US_UsuariosTranscriptoresCualitativos_Result)("US_UsuariosTranscriptoresCualitativos")
    End Function

    Public Overridable Function PY_SegmentosCuali_Moderadores_Get(segmentoId As Nullable(Of Long)) As ObjectResult(Of PY_SegmentosCuali_Moderadores_Get_Result)
        Dim segmentoIdParameter As ObjectParameter = If(segmentoId.HasValue, New ObjectParameter("SegmentoId", segmentoId), New ObjectParameter("SegmentoId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PY_SegmentosCuali_Moderadores_Get_Result)("PY_SegmentosCuali_Moderadores_Get", segmentoIdParameter)
    End Function

    Public Overridable Function PY_SegmentosCuali_Reclutadores_Get(segmentoId As Nullable(Of Long)) As ObjectResult(Of PY_SegmentosCuali_Reclutadores_Get_Result)
        Dim segmentoIdParameter As ObjectParameter = If(segmentoId.HasValue, New ObjectParameter("SegmentoId", segmentoId), New ObjectParameter("SegmentoId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PY_SegmentosCuali_Reclutadores_Get_Result)("PY_SegmentosCuali_Reclutadores_Get", segmentoIdParameter)
    End Function

    Public Overridable Function PY_TrabajoCuali_Get(idtrabajo As Nullable(Of Long)) As ObjectResult(Of PY_TrabajoCuali_Get_Result)
        Dim idtrabajoParameter As ObjectParameter = If(idtrabajo.HasValue, New ObjectParameter("Idtrabajo", idtrabajo), New ObjectParameter("Idtrabajo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PY_TrabajoCuali_Get_Result)("PY_TrabajoCuali_Get", idtrabajoParameter)
    End Function

    Public Overridable Function OP_LogSesionesCuali_Get(idSesion As Nullable(Of Long)) As ObjectResult(Of OP_LogSesionesCuali_Get_Result)
        Dim idSesionParameter As ObjectParameter = If(idSesion.HasValue, New ObjectParameter("IdSesion", idSesion), New ObjectParameter("IdSesion", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_LogSesionesCuali_Get_Result)("OP_LogSesionesCuali_Get", idSesionParameter)
    End Function

    Public Overridable Function OP_LogInHomeCuali_Get(idSesion As Nullable(Of Long)) As ObjectResult(Of OP_LogInHomeCuali_Get_Result)
        Dim idSesionParameter As ObjectParameter = If(idSesion.HasValue, New ObjectParameter("IdSesion", idSesion), New ObjectParameter("IdSesion", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_LogInHomeCuali_Get_Result)("OP_LogInHomeCuali_Get", idSesionParameter)
    End Function

    Public Overridable Function OP_EntrevistasCuali_DistribucionGet(id As Nullable(Of Long), idEntrevista As Nullable(Of Long), idtrabajo As Nullable(Of Long)) As ObjectResult(Of OP_EntrevistasCuali_DistribucionGet_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Dim idEntrevistaParameter As ObjectParameter = If(idEntrevista.HasValue, New ObjectParameter("IdEntrevista", idEntrevista), New ObjectParameter("IdEntrevista", GetType(Long)))

        Dim idtrabajoParameter As ObjectParameter = If(idtrabajo.HasValue, New ObjectParameter("Idtrabajo", idtrabajo), New ObjectParameter("Idtrabajo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_EntrevistasCuali_DistribucionGet_Result)("OP_EntrevistasCuali_DistribucionGet", idParameter, idEntrevistaParameter, idtrabajoParameter)
    End Function

    Public Overridable Function OP_LogEntrevistasCuali_Get(idDistribucion As Nullable(Of Long)) As ObjectResult(Of OP_LogEntrevistasCuali_Get_Result)
        Dim idDistribucionParameter As ObjectParameter = If(idDistribucion.HasValue, New ObjectParameter("IdDistribucion", idDistribucion), New ObjectParameter("IdDistribucion", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_LogEntrevistasCuali_Get_Result)("OP_LogEntrevistasCuali_Get", idDistribucionParameter)
    End Function

    Public Overridable Function OP_EntrevistasCuali_Distribucion_Add(cantidad As Nullable(Of Integer), idEntrevista As Nullable(Of Long), trabajoId As Nullable(Of Long), grupoObjetivo As String, ciudadId As Nullable(Of Integer), fechaInicio As Nullable(Of Date), fechaFin As Nullable(Of Date), moderador As Nullable(Of Long), usuario As Nullable(Of Long)) As Integer
        Dim cantidadParameter As ObjectParameter = If(cantidad.HasValue, New ObjectParameter("Cantidad", cantidad), New ObjectParameter("Cantidad", GetType(Integer)))

        Dim idEntrevistaParameter As ObjectParameter = If(idEntrevista.HasValue, New ObjectParameter("IdEntrevista", idEntrevista), New ObjectParameter("IdEntrevista", GetType(Long)))

        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Dim grupoObjetivoParameter As ObjectParameter = If(grupoObjetivo IsNot Nothing, New ObjectParameter("GrupoObjetivo", grupoObjetivo), New ObjectParameter("GrupoObjetivo", GetType(String)))

        Dim ciudadIdParameter As ObjectParameter = If(ciudadId.HasValue, New ObjectParameter("CiudadId", ciudadId), New ObjectParameter("CiudadId", GetType(Integer)))

        Dim fechaInicioParameter As ObjectParameter = If(fechaInicio.HasValue, New ObjectParameter("FechaInicio", fechaInicio), New ObjectParameter("FechaInicio", GetType(Date)))

        Dim fechaFinParameter As ObjectParameter = If(fechaFin.HasValue, New ObjectParameter("FechaFin", fechaFin), New ObjectParameter("FechaFin", GetType(Date)))

        Dim moderadorParameter As ObjectParameter = If(moderador.HasValue, New ObjectParameter("Moderador", moderador), New ObjectParameter("Moderador", GetType(Long)))

        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("OP_EntrevistasCuali_Distribucion_Add", cantidadParameter, idEntrevistaParameter, trabajoIdParameter, grupoObjetivoParameter, ciudadIdParameter, fechaInicioParameter, fechaFinParameter, moderadorParameter, usuarioParameter)
    End Function

    Public Overridable Function OP_Preguntas_Filtro_Get(idFiltro As Nullable(Of Long), tipoFiltro As Nullable(Of Integer), idTrabajo As Nullable(Of Long)) As ObjectResult(Of OP_Preguntas_Filtro_Get_Result)
        Dim idFiltroParameter As ObjectParameter = If(idFiltro.HasValue, New ObjectParameter("IdFiltro", idFiltro), New ObjectParameter("IdFiltro", GetType(Long)))

        Dim tipoFiltroParameter As ObjectParameter = If(tipoFiltro.HasValue, New ObjectParameter("TipoFiltro", tipoFiltro), New ObjectParameter("TipoFiltro", GetType(Integer)))

        Dim idTrabajoParameter As ObjectParameter = If(idTrabajo.HasValue, New ObjectParameter("IdTrabajo", idTrabajo), New ObjectParameter("IdTrabajo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_Preguntas_Filtro_Get_Result)("OP_Preguntas_Filtro_Get", idFiltroParameter, tipoFiltroParameter, idTrabajoParameter)
    End Function

    Public Overridable Function OP_Filtros_Get(idFiltro As Nullable(Of Long), tipoFiltro As Nullable(Of Integer), idTrabajo As Nullable(Of Long)) As ObjectResult(Of OP_Filtros_Get_Result)
        Dim idFiltroParameter As ObjectParameter = If(idFiltro.HasValue, New ObjectParameter("IdFiltro", idFiltro), New ObjectParameter("IdFiltro", GetType(Long)))

        Dim tipoFiltroParameter As ObjectParameter = If(tipoFiltro.HasValue, New ObjectParameter("TipoFiltro", tipoFiltro), New ObjectParameter("TipoFiltro", GetType(Integer)))

        Dim idTrabajoParameter As ObjectParameter = If(idTrabajo.HasValue, New ObjectParameter("IdTrabajo", idTrabajo), New ObjectParameter("IdTrabajo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_Filtros_Get_Result)("OP_Filtros_Get", idFiltroParameter, tipoFiltroParameter, idTrabajoParameter)
    End Function

    Public Overridable Function OP_Preguntas_Filtro_ActualizarOrden(idFiltro As Nullable(Of Long), ordenPregunta As Nullable(Of Integer)) As Integer
        Dim idFiltroParameter As ObjectParameter = If(idFiltro.HasValue, New ObjectParameter("IdFiltro", idFiltro), New ObjectParameter("IdFiltro", GetType(Long)))

        Dim ordenPreguntaParameter As ObjectParameter = If(ordenPregunta.HasValue, New ObjectParameter("OrdenPregunta", ordenPregunta), New ObjectParameter("OrdenPregunta", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("OP_Preguntas_Filtro_ActualizarOrden", idFiltroParameter, ordenPreguntaParameter)
    End Function

    Public Overridable Function OP_Preguntas_Filtro_ReOrdenar(idFiltro As Nullable(Of Long), ordenAnterior As Nullable(Of Integer), ordenActual As Nullable(Of Integer)) As Integer
        Dim idFiltroParameter As ObjectParameter = If(idFiltro.HasValue, New ObjectParameter("IdFiltro", idFiltro), New ObjectParameter("IdFiltro", GetType(Long)))

        Dim ordenAnteriorParameter As ObjectParameter = If(ordenAnterior.HasValue, New ObjectParameter("OrdenAnterior", ordenAnterior), New ObjectParameter("OrdenAnterior", GetType(Integer)))

        Dim ordenActualParameter As ObjectParameter = If(ordenActual.HasValue, New ObjectParameter("OrdenActual", ordenActual), New ObjectParameter("OrdenActual", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("OP_Preguntas_Filtro_ReOrdenar", idFiltroParameter, ordenAnteriorParameter, ordenActualParameter)
    End Function

    Public Overridable Function OP_Respuestas_FiltroReclutamiento_Maestro_Get(idTrabajo As Nullable(Of Long), cedula As Nullable(Of Long)) As ObjectResult(Of OP_Respuestas_FiltroReclutamiento_Maestro_Get_Result)
        Dim idTrabajoParameter As ObjectParameter = If(idTrabajo.HasValue, New ObjectParameter("IdTrabajo", idTrabajo), New ObjectParameter("IdTrabajo", GetType(Long)))

        Dim cedulaParameter As ObjectParameter = If(cedula.HasValue, New ObjectParameter("Cedula", cedula), New ObjectParameter("Cedula", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_Respuestas_FiltroReclutamiento_Maestro_Get_Result)("OP_Respuestas_FiltroReclutamiento_Maestro_Get", idTrabajoParameter, cedulaParameter)
    End Function

    Public Overridable Function OP_Filtros_CrearCopia(id As Nullable(Of Long), idFiltro As Nullable(Of Long)) As Integer
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("Id", id), New ObjectParameter("Id", GetType(Long)))

        Dim idFiltroParameter As ObjectParameter = If(idFiltro.HasValue, New ObjectParameter("IdFiltro", idFiltro), New ObjectParameter("IdFiltro", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("OP_Filtros_CrearCopia", idParameter, idFiltroParameter)
    End Function

    Public Overridable Function OP_Respuestas_Filtro_Detalle_Get(idRespuesta As Nullable(Of Long)) As ObjectResult(Of OP_Respuestas_Filtro_Detalle_Get_Result)
        Dim idRespuestaParameter As ObjectParameter = If(idRespuesta.HasValue, New ObjectParameter("IdRespuesta", idRespuesta), New ObjectParameter("IdRespuesta", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_Respuestas_Filtro_Detalle_Get_Result)("OP_Respuestas_Filtro_Detalle_Get", idRespuestaParameter)
    End Function

    Public Overridable Function OP_Respuestas_Filtro_Maestro_Get(idFiltro As Nullable(Of Long)) As ObjectResult(Of OP_Respuestas_Filtro_Maestro_Get_Result)
        Dim idFiltroParameter As ObjectParameter = If(idFiltro.HasValue, New ObjectParameter("IdFiltro", idFiltro), New ObjectParameter("IdFiltro", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_Respuestas_Filtro_Maestro_Get_Result)("OP_Respuestas_Filtro_Maestro_Get", idFiltroParameter)
    End Function

    Public Overridable Function OP_MuestraTrabajosCuali_EntrevistasGet(idMuestra As Nullable(Of Long), idtrabajo As Nullable(Of Long)) As ObjectResult(Of OP_MuestraTrabajosCuali_EntrevistasGet_Result)
        Dim idMuestraParameter As ObjectParameter = If(idMuestra.HasValue, New ObjectParameter("IdMuestra", idMuestra), New ObjectParameter("IdMuestra", GetType(Long)))

        Dim idtrabajoParameter As ObjectParameter = If(idtrabajo.HasValue, New ObjectParameter("Idtrabajo", idtrabajo), New ObjectParameter("Idtrabajo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_MuestraTrabajosCuali_EntrevistasGet_Result)("OP_MuestraTrabajosCuali_EntrevistasGet", idMuestraParameter, idtrabajoParameter)
    End Function

    Public Overridable Function OP_MuestraTrabajosCuali_InHomeGet(idMuestra As Nullable(Of Long), idtrabajo As Nullable(Of Long)) As ObjectResult(Of OP_MuestraTrabajosCuali_InHomeGet_Result)
        Dim idMuestraParameter As ObjectParameter = If(idMuestra.HasValue, New ObjectParameter("IdMuestra", idMuestra), New ObjectParameter("IdMuestra", GetType(Long)))

        Dim idtrabajoParameter As ObjectParameter = If(idtrabajo.HasValue, New ObjectParameter("Idtrabajo", idtrabajo), New ObjectParameter("Idtrabajo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_MuestraTrabajosCuali_InHomeGet_Result)("OP_MuestraTrabajosCuali_InHomeGet", idMuestraParameter, idtrabajoParameter)
    End Function

    Public Overridable Function OP_MuestraTrabajosCuali_SesionesGet(idMuestra As Nullable(Of Long), idtrabajo As Nullable(Of Long)) As ObjectResult(Of OP_MuestraTrabajosCuali_SesionesGet_Result)
        Dim idMuestraParameter As ObjectParameter = If(idMuestra.HasValue, New ObjectParameter("IdMuestra", idMuestra), New ObjectParameter("IdMuestra", GetType(Long)))

        Dim idtrabajoParameter As ObjectParameter = If(idtrabajo.HasValue, New ObjectParameter("Idtrabajo", idtrabajo), New ObjectParameter("Idtrabajo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_MuestraTrabajosCuali_SesionesGet_Result)("OP_MuestraTrabajosCuali_SesionesGet", idMuestraParameter, idtrabajoParameter)
    End Function

    Public Overridable Function OP_MuestraTrabajosCuali_Get(idMuestra As Nullable(Of Long), idtrabajo As Nullable(Of Long)) As ObjectResult(Of OP_MuestraTrabajosCuali_Get_Result)
        Dim idMuestraParameter As ObjectParameter = If(idMuestra.HasValue, New ObjectParameter("IdMuestra", idMuestra), New ObjectParameter("IdMuestra", GetType(Long)))

        Dim idtrabajoParameter As ObjectParameter = If(idtrabajo.HasValue, New ObjectParameter("Idtrabajo", idtrabajo), New ObjectParameter("Idtrabajo", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of OP_MuestraTrabajosCuali_Get_Result)("OP_MuestraTrabajosCuali_Get", idMuestraParameter, idtrabajoParameter)
    End Function

    Public Overridable Function PY_Trabajo_Entrega_Cualitativo(trabajoId As Nullable(Of Long)) As ObjectResult(Of PY_Trabajo_Entrega_Cualitativo_Result)
        Dim trabajoIdParameter As ObjectParameter = If(trabajoId.HasValue, New ObjectParameter("TrabajoId", trabajoId), New ObjectParameter("TrabajoId", GetType(Long)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PY_Trabajo_Entrega_Cualitativo_Result)("PY_Trabajo_Entrega_Cualitativo", trabajoIdParameter)
    End Function

End Class
