'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PY_EspecificacionesTrabajo
    Public Property TrabajoId As Long
    Public Property EspecifacionesCampo As String
    Public Property MaterialApoyo As String
    Public Property Incidencias As String
    Public Property PilotosCampo As String
    Public Property AuditoriaCampo As String
    Public Property Verificacion As String
    Public Property Critica As String
    Public Property PilotosCalidad As String
    Public Property Codificacion As String
    Public Property Procesamiento As String
    Public Property Estadistica As String
    Public Property OtrasEspecificaciones As String
    Public Property VCSeguridad As String
    Public Property VCObtencion As String
    Public Property VCGrupoObjetivo As String
    Public Property VCAplicacionInstrumentos As String
    Public Property VCDistribucionCuotas As String
    Public Property VCMetodologia As String

End Class
