'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PY_SegmentosCuali
    Public Property id As Long
    Public Property TrabajoId As Nullable(Of Long)
    Public Property Descripcion As String
    Public Property Cantidad As Nullable(Of Integer)
    Public Property ObservacionesMetodologia As String
    Public Property MetodoReclutamiento As String
    Public Property NoReclutadoras As Nullable(Of Integer)
    Public Property FechaInicio As Nullable(Of Date)
    Public Property FechaFin As Nullable(Of Date)
    Public Property Departamento As Nullable(Of Integer)
    Public Property Municipio As Nullable(Of Integer)
    Public Property TipoLugar As Nullable(Of Integer)
    Public Property EspecificacionesLugar As String
    Public Property NSE As String
    Public Property Edades As String
    Public Property Genero As String
    Public Property OtrasCaracteristicas As String
    Public Property ExclusionesYRestricciones As String
    Public Property NoPersonas As Nullable(Of Integer)
    Public Property GastosDeViaje As String
    Public Property Incentivos As String
    Public Property Alimentacion As String
    Public Property Transcripcion As Nullable(Of Boolean)
    Public Property Traduccion As Nullable(Of Boolean)
    Public Property Video As Nullable(Of Boolean)
    Public Property Audios As Nullable(Of Boolean)
    Public Property Filtros As Nullable(Of Boolean)
    Public Property FlashReport As Nullable(Of Boolean)
    Public Property OtrosEntregables As String
    Public Property ObservacionesGenerales As String
    Public Property OtrasAyudas As String

    Public Overridable Property OP_CampoCuali As ICollection(Of OP_CampoCuali) = New HashSet(Of OP_CampoCuali)
    Public Overridable Property PY_SegmentosCuali_Moderadores As ICollection(Of PY_SegmentosCuali_Moderadores) = New HashSet(Of PY_SegmentosCuali_Moderadores)
    Public Overridable Property PY_SegmentosCuali_Reclutadores As ICollection(Of PY_SegmentosCuali_Reclutadores) = New HashSet(Of PY_SegmentosCuali_Reclutadores)

End Class
