'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class t_Survey2016
    Public Property id As Long
    Public Property Nombres As String
    Public Property Apellidos As String
    Public Property AreaCargo As String
    Public Property Ciudad As String
    Public Property Q1 As Nullable(Of Integer)
    Public Property Q2 As Nullable(Of Integer)
    Public Property Q3 As Nullable(Of Integer)
    Public Property Q4 As Nullable(Of Integer)

End Class
