'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TH_ContratistasDetalleServicios
    Public Property Id As Long
    Public Property IdentificacionId As Nullable(Of Long)
    Public Property ServicioId As Nullable(Of Long)
    Public Property ServicioDescripcion As String
    Public Property Estado As Nullable(Of Boolean)

End Class
