'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TH_CapacitacionesParticipantes
    Public Property id As Long
    Public Property CapacitacionId As Nullable(Of Long)
    Public Property Participante As Nullable(Of Long)
    Public Property Eficacia As Nullable(Of Byte)
    Public Property OportunidadMejora As String
    Public Property Aprobo As Nullable(Of Boolean)

    Public Overridable Property TH_Capacitaciones As TH_Capacitaciones
    Public Overridable Property TH_Personas As TH_Personas

End Class
