'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TH_Capacitaciones
    Public Property id As Long
    Public Property Ubicacion As String
    Public Property Fecha As Nullable(Of Date)
    Public Property Duracion As Nullable(Of Byte)
    Public Property Actividad As String
    Public Property Responsable As Nullable(Of Long)
    Public Property Capacitador As String
    Public Property ObjetivoActividad As String
    Public Property ModoEvaluacion As String
    Public Property TrabajoId As Nullable(Of Long)

    Public Overridable Property PY_Trabajo As PY_Trabajo2
    Public Overridable Property TH_CapacitacionesParticipantes As ICollection(Of TH_CapacitacionesParticipantes) = New HashSet(Of TH_CapacitacionesParticipantes)

End Class
