'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TH_Evaluaciones
    Public Property Id As Long
    Public Property PersonaId As Nullable(Of Long)
    Public Property Fecha As Nullable(Of Date)
    Public Property Calificacion As Nullable(Of Double)
    Public Property Evaluador As String

End Class
