'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TH_LogPersonas
    Public Property Id As Long
    Public Property UsuarioId As Nullable(Of Long)
    Public Property Fecha As Nullable(Of Date)
    Public Property Campo As String
    Public Property ValorOriginal As String
    Public Property ValorNuevo As String
    Public Property PersonaId As Nullable(Of Long)

End Class
