'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TH_Personas
    Public Property id As Long
    Public Property Nombres As String
    Public Property Apellidos As String
    Public Property Cargo As Nullable(Of Long)
    Public Property CiudadId As Nullable(Of Integer)
    Public Property TipoContratacion As Nullable(Of Byte)
    Public Property FechaIngreso As Nullable(Of Date)
    Public Property FechaNacimiento As Nullable(Of Date)
    Public Property Activo As Nullable(Of Boolean)
    Public Property TipoId As Nullable(Of Integer)
    Public Property LugarExpedicion As String
    Public Property FechaExpedicion As Nullable(Of Date)
    Public Property Nacionalidad As String
    Public Property Sexo As String
    Public Property GrupoSanguineo As Nullable(Of Integer)
    Public Property EstadoCivil As Nullable(Of Integer)
    Public Property BarrioResidencia As String
    Public Property Direccion As String
    Public Property Telefono1 As String
    Public Property Telefono2 As String
    Public Property Celular As String
    Public Property EmailPersonal As String
    Public Property NivelEducativo As Nullable(Of Integer)
    Public Property Profesion As String
    Public Property BU As Nullable(Of Integer)
    Public Property Area As Nullable(Of Integer)
    Public Property Sede As Nullable(Of Integer)
    Public Property JefeInmediato As Nullable(Of Integer)
    Public Property Empresa As Nullable(Of Integer)
    Public Property TipoSalario As Nullable(Of Integer)
    Public Property FormaSalario As Nullable(Of Integer)
    Public Property SalarioActual As Nullable(Of Double)
    Public Property UltimoSalario As Nullable(Of Double)
    Public Property FechaUltimoAscenso As Nullable(Of Date)
    Public Property UltimoCargo As Nullable(Of Integer)
    Public Property EstadoActual As Nullable(Of Integer)
    Public Property FechaVencimientoContrato As Nullable(Of Date)
    Public Property FechaRetiro As Nullable(Of Date)
    Public Property MotivoRetiro As String
    Public Property Banco As Nullable(Of Integer)
    Public Property TipoCuenta As Nullable(Of Integer)
    Public Property CuentaBanco As String
    Public Property FondoPensiones As Nullable(Of Integer)
    Public Property FondoCesantias As Nullable(Of Integer)
    Public Property EPS As Nullable(Of Integer)
    Public Property CajaCompensacion As Nullable(Of Integer)
    Public Property ARL As Nullable(Of Integer)
    Public Property Contratista As Nullable(Of Long)
    Public Property NivelBI As Nullable(Of Integer)
    Public Property HeadCount As Nullable(Of Boolean)

    Public Overridable Property C_Divipola As C_Divipola2
    Public Overridable Property TH_CapacitacionesParticipantes As ICollection(Of TH_CapacitacionesParticipantes) = New HashSet(Of TH_CapacitacionesParticipantes)
    Public Overridable Property TH_Cargos As TH_Cargos
    Public Overridable Property TH_TipoContratacion As TH_TipoContratacion
    Public Overridable Property OP_Encuestadores As OP_Encuestadores
    Public Overridable Property OP_PersonasAsignadasTrabajo As ICollection(Of OP_PersonasAsignadasTrabajo) = New HashSet(Of OP_PersonasAsignadasTrabajo)

End Class
