'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TH_Personas3
    Public Property id As Long
    Public Property TipoId As Nullable(Of Integer)
    Public Property LugarExpedicion As String
    Public Property FechaExpedicion As Nullable(Of Date)
    Public Property Nombres As String
    Public Property Apellidos As String
    Public Property Nacionalidad As String
    Public Property Sexo As String
    Public Property GrupoSanguineo As Nullable(Of Integer)
    Public Property EstadoCivil As Nullable(Of Integer)
    Public Property FechaNacimiento As Nullable(Of Date)
    Public Property CiudadId As Nullable(Of Integer)
    Public Property BarrioResidencia As String
    Public Property Direccion As String
    Public Property Telefono1 As String
    Public Property Telefono2 As String
    Public Property Celular As String
    Public Property EmailPersonal As String
    Public Property NivelEducativo As Nullable(Of Integer)
    Public Property Profesion As String
    Public Property BU As Nullable(Of Integer)
    Public Property Area As Nullable(Of Integer)
    Public Property Sede As Nullable(Of Integer)
    Public Property Cargo As Nullable(Of Long)
    Public Property JefeInmediato As Nullable(Of Integer)
    Public Property FechaIngreso As Nullable(Of Date)
    Public Property TipoContratacion As Nullable(Of Byte)
    Public Property Empresa As Nullable(Of Integer)
    Public Property TipoSalario As Nullable(Of Integer)
    Public Property FormaSalario As Nullable(Of Integer)
    Public Property SalarioActual As Nullable(Of Double)
    Public Property UltimoSalario As Nullable(Of Double)
    Public Property FechaUltimoAscenso As Nullable(Of Date)
    Public Property UltimoCargo As Nullable(Of Integer)
    Public Property EstadoActual As Nullable(Of Integer)
    Public Property FechaVencimientoContrato As Nullable(Of Date)
    Public Property FechaRetiro As Nullable(Of Date)
    Public Property MotivoRetiro As String
    Public Property Banco As Nullable(Of Integer)
    Public Property TipoCuenta As Nullable(Of Integer)
    Public Property CuentaBanco As String
    Public Property FondoPensiones As Nullable(Of Integer)
    Public Property FondoCesantias As Nullable(Of Integer)
    Public Property EPS As Nullable(Of Integer)
    Public Property CajaCompensacion As Nullable(Of Integer)
    Public Property ARL As Nullable(Of Integer)
    Public Property Activo As Nullable(Of Boolean)
    Public Property Contratista As Nullable(Of Long)
    Public Property NivelBI As Nullable(Of Integer)
    Public Property HeadCount As Nullable(Of Boolean)
    Public Property IdIStaff As Nullable(Of Long)
    Public Property levelId As Nullable(Of Byte)
    Public Property bandaId As Nullable(Of Byte)
    Public Property urlFoto As String
    Public Property nombrePreferido As String
    Public Property correoIpsos As String
    Public Property fechaCreacion As Nullable(Of Date)
    Public Property fechaUltimaActualizacion As Nullable(Of Date)
    Public Property usuarioRegistro As Nullable(Of Long)
    Public Property centroCostoId As Nullable(Of Integer)
    Public Property tiempoContratoId As Nullable(Of Byte)
    Public Property nseId As Nullable(Of Byte)
    Public Property localidadId As Nullable(Of Byte)
    Public Property nivelInglesId As Nullable(Of Byte)
    Public Property jobFunctionId As Nullable(Of Byte)
    Public Property observaciones As String
    Public Property loginIfield As String
    Public Property municipioNacimientoDivipolaId As Nullable(Of Integer)
    Public Property TallaCamisetaId As Nullable(Of Byte)

    Public Overridable Property C_Divipola As C_Divipola
    Public Overridable Property OP_EncuestasAnuladas As ICollection(Of OP_EncuestasAnuladas) = New HashSet(Of OP_EncuestasAnuladas)

End Class
