'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TH_SolicitudAusencia
    Public Property id As Long
    Public Property idEmpleado As Long
    Public Property FiniCausacion As Nullable(Of Date)
    Public Property FFinCausacion As Nullable(Of Date)
    Public Property FInicio As Date
    Public Property FFin As Date
    Public Property DiasCalendario As Nullable(Of Short)
    Public Property DiasLaborales As Nullable(Of Byte)
    Public Property Tipo As Nullable(Of Byte)
    Public Property Estado As Nullable(Of Byte)
    Public Property AprobadoPor As Nullable(Of Long)
    Public Property FechaAprobacion As Nullable(Of Date)
    Public Property VoBo1 As Nullable(Of Long)
    Public Property FechaVoBo1 As Nullable(Of Date)
    Public Property VoBo2 As Nullable(Of Long)
    Public Property FechaVoBo2 As Nullable(Of Date)
    Public Property VoBo3 As Nullable(Of Long)
    Public Property FechaVoBo3 As Nullable(Of Date)
    Public Property RegistradoPor As Nullable(Of Long)
    Public Property FechaRegistro As Nullable(Of Date)
    Public Property ObservacionesSolicitud As String
    Public Property ObservacionesAprobacion As String

End Class
