'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class US_JefesUnidades
    Public Property id As Long
    Public Property UnidadId As Nullable(Of Integer)
    Public Property UsuarioId As Nullable(Of Long)
    Public Property Nivel As Nullable(Of Short)

End Class
