'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class US_UsuariosOP
    Public Property id As Long
    Public Property Usuario As String
    Public Property Password As String
    Public Property Nombres As String
    Public Property Apellidos As String
    Public Property Email As String
    Public Property Activo As Nullable(Of Boolean)

    Public Overridable Property OP_TraficoEncuestas As ICollection(Of OP_TraficoEncuestas) = New HashSet(Of OP_TraficoEncuestas)
    Public Overridable Property OP_TraficoEncuestas1 As ICollection(Of OP_TraficoEncuestas) = New HashSet(Of OP_TraficoEncuestas)

End Class
