'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class US_Usuarios3
    Public Property id As Long
    Public Property Usuario As String
    Public Property Password As String
    Public Property Nombres As String
    Public Property Apellidos As String
    Public Property Email As String
    Public Property Activo As Nullable(Of Boolean)

    Public Overridable Property CORE_Retroalimentacion As ICollection(Of CORE_Retroalimentacion) = New HashSet(Of CORE_Retroalimentacion)
    Public Overridable Property CORE_Retroalimentacion1 As ICollection(Of CORE_Retroalimentacion) = New HashSet(Of CORE_Retroalimentacion)
    Public Overridable Property CORE_WorkFlow_UsuariosAsignados As ICollection(Of CORE_WorkFlow_UsuariosAsignados) = New HashSet(Of CORE_WorkFlow_UsuariosAsignados)
    Public Overridable Property US_RolesUsuarios As ICollection(Of US_RolesUsuarios2) = New HashSet(Of US_RolesUsuarios2)

End Class
