'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PNC_Productos
    
    '''<summary>
    '''cantProdRecibibos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cantProdRecibibos As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cantProdEnviados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cantProdEnviados As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pnlProductos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProductos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upProductos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upProductos As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''gvDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDatos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upWizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upWizard As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlWizard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWizard As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''upProductosCausas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upProductosCausas As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlProductosCausas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProductosCausas As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblAsociadoA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAsociadoA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNombreProyectoTrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreProyectoTrabajo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProceso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProcedimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProcedimiento As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechaReclamo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaReclamo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFuente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoria As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarea As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUnidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnidad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblIdentifica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdentifica As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblResponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResponsable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInformar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInformar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnAceptar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRechazar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRechazar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtCausa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCausa As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCorreccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorreccion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFechaEstimadaCierre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaEstimadaCierre As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnRegresarProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegresarProducto As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGrabarCausa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabarCausa As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtRechazo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRechazo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnRegresarDesdeRechazo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegresarDesdeRechazo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnGrabarRechazo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGrabarRechazo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''upDiligenciarProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDiligenciarProducto As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlAsociadoA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAsociadoA As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlProcedimientos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProcedimientos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlFuente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFuente As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlResponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResponsable As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlBuscarJBIJBE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBuscarJBIJBE As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnBuscarProyectoEstudio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarProyectoEstudio As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblId_PT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblId_PT As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNombre_PT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombre_PT As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlUnidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUnidad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategoria As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlInformar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInformar As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlProcesos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProcesos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlIdentifica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIdentifica As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlTarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTarea As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFechaReclamo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaReclamo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnEnviar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnviar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRegistrarNuevoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistrarNuevoProducto As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''upJBEJBICC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upJBEJBICC As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtJBEJBICC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJBEJBICC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnBuscarJBEJBICC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarJBEJBICC As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvJBEJBICC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvJBEJBICC As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''upProductosEnviados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upProductosEnviados As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''gvProductosEnviados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProductosEnviados As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''pnlProductoEnviado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProductoEnviado As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbl_PE_AsociadoA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_AsociadoA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Nombre As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Proceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Proceso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Procedimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Procedimiento As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_FechaReclamo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_FechaReclamo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Fuente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Fuente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Categoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Categoria As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Tarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Tarea As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Unidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Unidad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Identifica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Identifica As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Responsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Responsable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Informar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Informar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_PE_Descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PE_Descripcion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnMostrarRespuestaProductoEnviado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMostrarRespuestaProductoEnviado As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblRegistroCausa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistroCausa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divRespuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRespuesta As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblCausa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCausa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCorreccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorreccion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechaEstimadaCierre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaEstimadaCierre As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divRechazo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divRechazo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblRechazo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRechazo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnMostrarProductoEnviado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMostrarProductoEnviado As Global.System.Web.UI.WebControls.Button
End Class
