'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SyncIssues

    '''<summary>
    '''upDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDatos As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtNumeroTrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroTrabajo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnQuitarEntrenamiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitarEntrenamiento As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSupervision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSupervision As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSincronizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSincronizacion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtTrabajoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTrabajoId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlPreguntas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPreguntas As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSbjNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSbjNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNewValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnActualizarValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnActualizarValor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtSbjNumPiloto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSbjNumPiloto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHabilitarPiloto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHabilitarPiloto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtSbjNumPiloto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSbjNumPiloto2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnEncuestaPiloto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEncuestaPiloto As Global.System.Web.UI.WebControls.Button
End Class
