Option Strict On
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Net
Imports System.Web.Script.Services
Imports CoreProject.DesvinculacionEmpleadosDapper

Partial Public Class DesvinculacionesEmpleadosGestionArea
    Inherits System.Web.UI.Page

    Shared desvinculacionEmpleadosRepository As New DesvinculacionEmpleadosDapper
    Shared emailSender As New EnviarCorreo()

    <Services.WebMethod()>
    <ScriptMethod(ResponseFormat:=ResponseFormat.Json)>
    Public Shared Function ProcesosDesvinculacionPendientesPorArea(AreaId As Integer) As List(Of DesvinculacionEmpleadoPendientePorEvaluarArea)
        Return desvinculacionEmpleadosRepository.PendientesPorEvaluarPorArea(AreaId)
    End Function
    <Services.WebMethod()>
    <ScriptMethod(ResponseFormat:=ResponseFormat.Json)>
    Public Shared Function ProcesosDesvinculacionPendientesPorEvaluarUsuarioActual() As List(Of DesvinculacionEmpleadoPendienteEvaluarPorEvaluador)
        Dim usuarioActualId As Long = Long.Parse(HttpContext.Current.Session("IDUsuario").ToString())
        Return desvinculacionEmpleadosRepository.PendientesPorEvaluarPorEvaluador(usuarioActualId)
    End Function

    <Services.WebMethod()>
    <ScriptMethod(ResponseFormat:=ResponseFormat.Json)>
    Public Shared Function ProcesosDesvinculacionItemsVerificarPor(AreaId As Integer) As List(Of DesvinculacionEmpleadosAreaItemVerificar)
        Return desvinculacionEmpleadosRepository.ItemsVerificarPor(AreaId)
    End Function
    <Services.WebMethod()>
    <ScriptMethod(ResponseFormat:=ResponseFormat.Json)>
    Public Shared Function InformacionEmpleadoPor(DesvinculacionEmpleadoId As Integer) As DesvinculacionEmpleadoEmpleadoInfo
        Return desvinculacionEmpleadosRepository.InformacionEmpleadoPor(DesvinculacionEmpleadoId)
    End Function
    <Services.WebMethod()>
    <ScriptMethod(ResponseFormat:=ResponseFormat.Json)>
    Public Shared Sub GuardarEvaluacion(DesvinculacionEmpleadoEvaluacion As DesvinculacionEmpleadoEvaluacionModel)
        If DesvinculacionEmpleadoEvaluacion Is Nothing Then
            HttpContext.Current.Response.StatusCode = HttpStatusCode.BadRequest
            Return
        End If

        If String.IsNullOrWhiteSpace(DesvinculacionEmpleadoEvaluacion.Comentarios) Then
            HttpContext.Current.Response.StatusCode = HttpStatusCode.BadRequest
            Return
        End If

        desvinculacionEmpleadosRepository.GuardarEvaluacion(Map(DesvinculacionEmpleadoEvaluacion))
        If Not TieneEvaluacionesPendientes(DesvinculacionEmpleadoEvaluacion.DesvinculacionEmpleadoId) Then
            FinalizarProcesoDesvinculacion(DesvinculacionEmpleadoEvaluacion.DesvinculacionEmpleadoId)
        End If
    End Sub

    Private Shared Function Map(Model As DesvinculacionEmpleadoEvaluacionModel) As DesvinculacionEmpleadoEvaluacionArea
        Dim usuarioActualId As Long = Long.Parse(HttpContext.Current.Session("IDUsuario").ToString())
        Return New DesvinculacionEmpleadoEvaluacionArea() With {
            .DesvinculacionEmpleadoId = Model.DesvinculacionEmpleadoId,
            .Comentarios = Model.Comentarios,
            .FechaDiligenciamiento = DateTime.UtcNow.AddHours(-5),
            .AreaId = Model.AreaId,
            .UsuarioRegistra = usuarioActualId
            }
    End Function

    <Services.WebMethod()>
    <ScriptMethod(ResponseFormat:=ResponseFormat.Json)>
    Public Shared Function EvaluacionesRealizadasPorUsuarioActual() As List(Of DesvinculacionEmpleadoEvaluacionRealizadaPorEvaluador)
        Dim usuarioActualId As Long = Long.Parse(HttpContext.Current.Session("IDUsuario").ToString())
        Return desvinculacionEmpleadosRepository.EvaluacionesRealizadasPorEvaluador(usuarioActualId)
    End Function
    Private Shared Function TieneEvaluacionesPendientes(desvinculacionEmpleadoId As Integer) As Boolean
        Dim evaluaciones = DesvinculacionesEmpleadosGestionRRHH.DesvinculacionEmpleadosEstatusEvaluacionesPor(desvinculacionEmpleadoId)
        Return evaluaciones.Any(Function(x) x.Estado = "Pendiente")
    End Function
    Private Shared Sub FinalizarProcesoDesvinculacion(desvinculacionEmpleadoId As Long)
        desvinculacionEmpleadosRepository.FinalizarProceso(desvinculacionEmpleadoId)
        emailSender.enviarCorreo(WebMatrix.Util.obtenerUrlRaiz() & "/Emails/DesvinculacionEmpleadoFinProceso.aspx?idProcesoDesvinculacion=" & desvinculacionEmpleadoId)
    End Sub

    Public Class DesvinculacionEmpleadoEvaluacionModel
        Property DesvinculacionEmpleadoId As Integer
        Property AreaId As Integer
        Property Comentarios As String
    End Class

End Class
