'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportesIndicadoresCronogramaTareas
    
    '''<summary>
    '''btnExportarExcelVariablesControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportarExcelVariablesControl As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlTrabajosConTareaEntregaProyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTrabajosConTareaEntregaProyecto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''upCargarIndicadoresTrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCargarIndicadoresTrabajo As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnCargarIndicadoresTrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCargarIndicadoresTrabajo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''upIndicadoresPorTrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upIndicadoresPorTrabajo As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''gvIndicadoresPorTrabajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvIndicadoresPorTrabajo As Global.System.Web.UI.WebControls.GridView
End Class
