'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportesMedicionProgramaProyectos

	'''<summary>
	'''lblAno control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAno As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlAno control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlAno As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblMes control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMes As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlMes control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlMes As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblTareas control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTareas As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlTareas control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTareas As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblInstrumento control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblInstrumento As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlInstrumentos control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlInstrumentos As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblVerPor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblVerPor As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlVerPor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlVerPor As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnAcualizar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAcualizar As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''updDatos control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents updDatos As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''gvDatosGerente control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvDatosGerente As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnExcelDetalleGerente control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnExcelDetalleGerente As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''updDatosDetalle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents updDatosDetalle As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''gvDatosDetalleGerente control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvDatosDetalleGerente As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''UpdatePanel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''gvDatosResponsable control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvDatosResponsable As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnExcelDetalleResponsable control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnExcelDetalleResponsable As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''UpdatePanel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''gvDatosDetalleResponsable control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvDatosDetalleResponsable As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''UpdatePanel3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''gvDatosCOE control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvDatosCOE As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnExcelDetalleCOE control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnExcelDetalleCOE As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''UpdatePanel4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''gvDatosDetalleCOE control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvDatosDetalleCOE As Global.System.Web.UI.WebControls.GridView
End Class
