'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PropuestasSinTrabajo

    '''<summary>
    '''GVPropuestasPorUnidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPropuestasPorUnidad As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PropuestasPorUnidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropuestasPorUnidad As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''GVPropuestasMetodologia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPropuestasMetodologia As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PropuestasPorMetodologia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropuestasPorMetodologia As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btTotales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btTotales As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GVPropuestasRelacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPropuestasRelacion As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PropuestasRelacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropuestasRelacion As Global.System.Web.UI.WebControls.SqlDataSource
End Class
