'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AsignacionesProyectos

    '''<summary>
    '''btnAsignacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAsignacion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReasignacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReasignacion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlUnidades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUnidades As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UPanelSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPanelSearch As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lkbModalGP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkbModalGP As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ModalPopupExtenderGP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupExtenderGP As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlAsignacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAsignacion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvDataProyectos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDataProyectos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlReasignacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReasignacion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvDataProyectosReasignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDataProyectosReasignar As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlGP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UPanelClonar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPanelClonar As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hfIDProyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIDProyecto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIdUnidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdUnidad As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUsuarios As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelClone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelClone As Global.System.Web.UI.WebControls.Button
End Class
