'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InstructivoGeneralCuali
    
    '''<summary>
    '''upDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upDatos As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hfTrabajoID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTrabajoID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfversion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfversion As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pVersion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtModerador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModerador As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEspecificacionesCampo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEspecificacionesCampo As Global.AjaxControlToolkit.HTMLEditor.Editor
    
    '''<summary>
    '''lblEspecificacionesCampo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEspecificacionesCampo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMaterialApoyo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaterialApoyo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtIncidencias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIncidencias As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAuditoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuditoria As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVCSeguridad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVCSeguridad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVCObtencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVCObtencion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVCGrupoObjetivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVCGrupoObjetivo As Global.AjaxControlToolkit.HTMLEditor.Editor
    
    '''<summary>
    '''lblVCGrupoObjetivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVCGrupoObjetivo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtVCAplicacionInstrumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVCAplicacionInstrumentos As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVCDistribucionCuotas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVCDistribucionCuotas As Global.AjaxControlToolkit.HTMLEditor.Editor
    
    '''<summary>
    '''lblVCDistribucionCuotas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVCDistribucionCuotas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtVCMetodologia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVCMetodologia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblIncentivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIncentivos As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtPresupuestoIncentivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPresupuestoIncentivo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDistribucionIncentivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistribucionIncentivo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblRegaloClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblRegaloClientes As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblCompraIpsos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCompraIpsos As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtPresupuestoCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPresupuestoCompra As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDistribucionCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistribucionCompra As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chbAyudas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chbAyudas As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''chbReclutamiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chbReclutamiento As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''txtExclusionesyRestricciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExclusionesyRestricciones As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRecursosPropiedadesCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecursosPropiedadesCliente As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHabeasData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHabeasData As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOtrasEspecificaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtrasEspecificaciones As Global.AjaxControlToolkit.HTMLEditor.Editor
    
    '''<summary>
    '''lblOtrasEspecificaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOtrasEspecificaciones As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRegresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegresar As Global.System.Web.UI.WebControls.Button
End Class
