'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MBO_Operaciones

    '''<summary>
    '''BusyBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BusyBox1 As Global.BusyBoxDotNet.BusyBox

    '''<summary>
    '''AñoActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AñoActual As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CalidadMesTotalAñoActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalidadMesTotalAñoActual As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''AñoAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AñoAnterior As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CalidadMesTotalAñoAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalidadMesTotalAñoAnterior As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''GVCampoCalidadTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVCampoCalidadTotal As Global.System.Web.UI.WebControls.GridView
End Class
